/*
Hypixel Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// SkyBlockProfileMemberPlayerDataVisitedZonesInner the model 'SkyBlockProfileMemberPlayerDataVisitedZonesInner'
type SkyBlockProfileMemberPlayerDataVisitedZonesInner string

// List of SkyBlockProfileMemberPlayerData_visited_zones_inner
const (
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_ABANDONED_QUARRY                  SkyBlockProfileMemberPlayerDataVisitedZonesInner = "abandoned_quarry"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_ARACHNES_BURROW                   SkyBlockProfileMemberPlayerDataVisitedZonesInner = "arachnes_burrow"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_ARACHNES_SANCTUARY                SkyBlockProfileMemberPlayerDataVisitedZonesInner = "arachnes_sanctuary"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_ARCHAEOLOGIST_CAMP                SkyBlockProfileMemberPlayerDataVisitedZonesInner = "archaeologist_camp"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_ARCHERY_RANGE                     SkyBlockProfileMemberPlayerDataVisitedZonesInner = "archery_range"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_ARISTOCRAT_PASSAGE                SkyBlockProfileMemberPlayerDataVisitedZonesInner = "aristocrat_passage"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_ARTIST_ABODE                      SkyBlockProfileMemberPlayerDataVisitedZonesInner = "artist_abode"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_ASHFANG_RUINS                     SkyBlockProfileMemberPlayerDataVisitedZonesInner = "ashfang_ruins"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_AUCTION_HOUSE                     SkyBlockProfileMemberPlayerDataVisitedZonesInner = "auction_house"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_AURA_LABORATORY                   SkyBlockProfileMemberPlayerDataVisitedZonesInner = "aura_laboratory"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_BACK_2_BASICS                     SkyBlockProfileMemberPlayerDataVisitedZonesInner = "back_2_basics"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_BACKWATER_BAYOU                   SkyBlockProfileMemberPlayerDataVisitedZonesInner = "backwater_bayou"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_BANK                              SkyBlockProfileMemberPlayerDataVisitedZonesInner = "bank"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_BARBARIAN_OUTPOST                 SkyBlockProfileMemberPlayerDataVisitedZonesInner = "barbarian_outpost"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_BARRY_CENTER                      SkyBlockProfileMemberPlayerDataVisitedZonesInner = "barry_center"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_BARRY_HQ                          SkyBlockProfileMemberPlayerDataVisitedZonesInner = "barry_hq"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_BARTER_BANK                       SkyBlockProfileMemberPlayerDataVisitedZonesInner = "barter_bank"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_BASTION                           SkyBlockProfileMemberPlayerDataVisitedZonesInner = "bastion"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_BAZAAR_ALLEY                      SkyBlockProfileMemberPlayerDataVisitedZonesInner = "bazaar_alley"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_BEANSTALK                         SkyBlockProfileMemberPlayerDataVisitedZonesInner = "beanstalk"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_BLACK_LAGOON                      SkyBlockProfileMemberPlayerDataVisitedZonesInner = "black_lagoon"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_BLACKSMITH                        SkyBlockProfileMemberPlayerDataVisitedZonesInner = "blacksmith"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_BLAZING_FORTRESS                  SkyBlockProfileMemberPlayerDataVisitedZonesInner = "blazing_fortress"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_BLAZING_VOLCANO                   SkyBlockProfileMemberPlayerDataVisitedZonesInner = "blazing_volcano"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_BOOKCEPTION                       SkyBlockProfileMemberPlayerDataVisitedZonesInner = "bookception"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_BREAKABLE_TNT_WALL                SkyBlockProfileMemberPlayerDataVisitedZonesInner = "breakable_tnt_wall"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_BUILDERS_HOUSE                    SkyBlockProfileMemberPlayerDataVisitedZonesInner = "builders_house"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_BURNING_DESERT                    SkyBlockProfileMemberPlayerDataVisitedZonesInner = "burning_desert"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_CAKE_HOUSE                        SkyBlockProfileMemberPlayerDataVisitedZonesInner = "cake_house"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_CANVAS_ROOM                       SkyBlockProfileMemberPlayerDataVisitedZonesInner = "canvas_room"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_CARNIVAL                          SkyBlockProfileMemberPlayerDataVisitedZonesInner = "carnival"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_CARTS_CRAFTING_CO                 SkyBlockProfileMemberPlayerDataVisitedZonesInner = "carts_crafting_co"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_CATACOMBS_ENTRANCE                SkyBlockProfileMemberPlayerDataVisitedZonesInner = "catacombs_entrance"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_CATHEDRAL                         SkyBlockProfileMemberPlayerDataVisitedZonesInner = "cathedral"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_CAVE_GLOWING_MUSHROOM             SkyBlockProfileMemberPlayerDataVisitedZonesInner = "cave_glowing_mushroom"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_CLIFFSIDE_VEINS                   SkyBlockProfileMemberPlayerDataVisitedZonesInner = "cliffside_veins"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_COLOSSEUM                         SkyBlockProfileMemberPlayerDataVisitedZonesInner = "colosseum"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_COLOSSEUM_ARENA                   SkyBlockProfileMemberPlayerDataVisitedZonesInner = "colosseum_arena"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_COMMUNITY_CENTER                  SkyBlockProfileMemberPlayerDataVisitedZonesInner = "community_center"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_CONTINUUM                         SkyBlockProfileMemberPlayerDataVisitedZonesInner = "continuum"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_CRIMSON_FIELDS                    SkyBlockProfileMemberPlayerDataVisitedZonesInner = "crimson_fields"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_CRIMSON_ISLE                      SkyBlockProfileMemberPlayerDataVisitedZonesInner = "crimson_isle"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_DANGER                            SkyBlockProfileMemberPlayerDataVisitedZonesInner = "danger"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_DARK_AUCTION                      SkyBlockProfileMemberPlayerDataVisitedZonesInner = "dark_auction"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_DEEP_CAVERNS                      SkyBlockProfileMemberPlayerDataVisitedZonesInner = "deep_caverns"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_DEEP_CAVERNS_ROOM_1               SkyBlockProfileMemberPlayerDataVisitedZonesInner = "deep_caverns_room_1"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_DEEP_CAVERNS_ROOM_2               SkyBlockProfileMemberPlayerDataVisitedZonesInner = "deep_caverns_room_2"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_DEEP_CAVERNS_ROOM_3               SkyBlockProfileMemberPlayerDataVisitedZonesInner = "deep_caverns_room_3"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_DEEP_CAVERNS_ROOM_4               SkyBlockProfileMemberPlayerDataVisitedZonesInner = "deep_caverns_room_4"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_DEEP_CAVERNS_ROOM_5               SkyBlockProfileMemberPlayerDataVisitedZonesInner = "deep_caverns_room_5"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_DEEP_CAVERNS_ROOM_6               SkyBlockProfileMemberPlayerDataVisitedZonesInner = "deep_caverns_room_6"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_DEEPER_CAVERNS                    SkyBlockProfileMemberPlayerDataVisitedZonesInner = "deeper_caverns"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_DEEPER_CAVERNS_LIFT               SkyBlockProfileMemberPlayerDataVisitedZonesInner = "deeper_caverns_lift"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_DEJA_VU_ALLEY                     SkyBlockProfileMemberPlayerDataVisitedZonesInner = "deja_vu_alley"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_DESERT_MOUNTAIN                   SkyBlockProfileMemberPlayerDataVisitedZonesInner = "desert_mountain"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_DESERT_SETTLEMENT                 SkyBlockProfileMemberPlayerDataVisitedZonesInner = "desert_settlement"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_DIVAN_GATEWAY                     SkyBlockProfileMemberPlayerDataVisitedZonesInner = "divan_gateway"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_DOJO                              SkyBlockProfileMemberPlayerDataVisitedZonesInner = "dojo"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_DOJO_ARENA                        SkyBlockProfileMemberPlayerDataVisitedZonesInner = "dojo_arena"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_DRAGONTAIL_CHIEF_HUT              SkyBlockProfileMemberPlayerDataVisitedZonesInner = "dragontail_chief_hut"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_DRAGONTAIL_MINION_SHOP            SkyBlockProfileMemberPlayerDataVisitedZonesInner = "dragontail_minion_shop"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_DRAGONTAIL_TOWN                   SkyBlockProfileMemberPlayerDataVisitedZonesInner = "dragontail_town"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_DRAGONTAIL_TOWN_AUCTION_HOUSE     SkyBlockProfileMemberPlayerDataVisitedZonesInner = "dragontail_town_auction_house"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_DRAGONTAIL_TOWN_BANK              SkyBlockProfileMemberPlayerDataVisitedZonesInner = "dragontail_town_bank"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_DRAGONTAIL_TOWN_BAZAAR            SkyBlockProfileMemberPlayerDataVisitedZonesInner = "dragontail_town_bazaar"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_DRAGONTAIL_TOWN_BLACKSMITH        SkyBlockProfileMemberPlayerDataVisitedZonesInner = "dragontail_town_blacksmith"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_DRAGONTAIL_TOWN_SQUARE            SkyBlockProfileMemberPlayerDataVisitedZonesInner = "dragontail_town_square"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_DREADFARM                         SkyBlockProfileMemberPlayerDataVisitedZonesInner = "dreadfarm"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_DUEL_ZONE                         SkyBlockProfileMemberPlayerDataVisitedZonesInner = "duel_zone"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_DUNGEON                           SkyBlockProfileMemberPlayerDataVisitedZonesInner = "dungeon"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_DUNGEON_HUB                       SkyBlockProfileMemberPlayerDataVisitedZonesInner = "dungeon_hub"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_DWARVEN_BASE_CAMP                 SkyBlockProfileMemberPlayerDataVisitedZonesInner = "dwarven_base_camp"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_DWARVEN_TAVERN                    SkyBlockProfileMemberPlayerDataVisitedZonesInner = "dwarven_tavern"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_DWARVEN_VILLAGE                   SkyBlockProfileMemberPlayerDataVisitedZonesInner = "dwarven_village"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_DYNAMIC_PORTAL_ISLAND             SkyBlockProfileMemberPlayerDataVisitedZonesInner = "dynamic_portal_island"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_EINARYS_EMPORIUM                  SkyBlockProfileMemberPlayerDataVisitedZonesInner = "einarys_emporium"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_ELDER_PALACE                      SkyBlockProfileMemberPlayerDataVisitedZonesInner = "elder_palace"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_ELECTION_ROOM                     SkyBlockProfileMemberPlayerDataVisitedZonesInner = "election_room"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_ENDERDRAGON_BOSS_ROOM             SkyBlockProfileMemberPlayerDataVisitedZonesInner = "enderdragon_boss_room"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_ENDERMAN_SANCTUARY                SkyBlockProfileMemberPlayerDataVisitedZonesInner = "enderman_sanctuary"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_ENIGMA                            SkyBlockProfileMemberPlayerDataVisitedZonesInner = "enigma"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_FAR_RESERVE                       SkyBlockProfileMemberPlayerDataVisitedZonesInner = "far_reserve"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_FARM                              SkyBlockProfileMemberPlayerDataVisitedZonesInner = "farm"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_FARMHOUSE                         SkyBlockProfileMemberPlayerDataVisitedZonesInner = "farmhouse"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_FISHERMAN_HUT                     SkyBlockProfileMemberPlayerDataVisitedZonesInner = "fisherman_hut"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_FISHING_OUTPOST                   SkyBlockProfileMemberPlayerDataVisitedZonesInner = "fishing_outpost"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_FLOATING_ISLANDS_1                SkyBlockProfileMemberPlayerDataVisitedZonesInner = "floating_islands_1"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_FLOATING_ISLANDS_2                SkyBlockProfileMemberPlayerDataVisitedZonesInner = "floating_islands_2"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_FLOATING_ISLANDS_3                SkyBlockProfileMemberPlayerDataVisitedZonesInner = "floating_islands_3"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_FLOATING_ISLANDS_4                SkyBlockProfileMemberPlayerDataVisitedZonesInner = "floating_islands_4"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_FLOATING_ISLANDS_5                SkyBlockProfileMemberPlayerDataVisitedZonesInner = "floating_islands_5"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_FLOWER_HOUSE                      SkyBlockProfileMemberPlayerDataVisitedZonesInner = "flower_house"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_FOREST                            SkyBlockProfileMemberPlayerDataVisitedZonesInner = "forest"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_FORGE                             SkyBlockProfileMemberPlayerDataVisitedZonesInner = "forge"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_FORGE_BASIN                       SkyBlockProfileMemberPlayerDataVisitedZonesInner = "forge_basin"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_FORGOTTEN_SKULL                   SkyBlockProfileMemberPlayerDataVisitedZonesInner = "forgotten_skull"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_FOSSIL_RESEARCH_CENTER            SkyBlockProfileMemberPlayerDataVisitedZonesInner = "fossil_research_center"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_GARYS_SHACK                       SkyBlockProfileMemberPlayerDataVisitedZonesInner = "garys_shack"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_GATES_MINES                       SkyBlockProfileMemberPlayerDataVisitedZonesInner = "gates_mines"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_GLACIAL_CAVE                      SkyBlockProfileMemberPlayerDataVisitedZonesInner = "glacial_cave"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_GLACITE_LAKE                      SkyBlockProfileMemberPlayerDataVisitedZonesInner = "glacite_lake"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_GLACITE_TUNNELS                   SkyBlockProfileMemberPlayerDataVisitedZonesInner = "glacite_tunnels"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_GOBLIN_BURROWS                    SkyBlockProfileMemberPlayerDataVisitedZonesInner = "goblin_burrows"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_GOLD_MINE                         SkyBlockProfileMemberPlayerDataVisitedZonesInner = "gold_mine"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_GORGE                             SkyBlockProfileMemberPlayerDataVisitedZonesInner = "gorge"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_GRAND_LIBRARY                     SkyBlockProfileMemberPlayerDataVisitedZonesInner = "grand_library"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_GRANDMAS_HOUSE                    SkyBlockProfileMemberPlayerDataVisitedZonesInner = "grandmas_house"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_GRAVEL_MINES                      SkyBlockProfileMemberPlayerDataVisitedZonesInner = "gravel_mines"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_GREATER_MINES                     SkyBlockProfileMemberPlayerDataVisitedZonesInner = "greater_mines"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_GREATER_MINES_CRYSTAL_ROOM        SkyBlockProfileMemberPlayerDataVisitedZonesInner = "greater_mines_crystal_room"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_GREATER_MINES_FAIRY_GROTTO        SkyBlockProfileMemberPlayerDataVisitedZonesInner = "greater_mines_fairy_grotto"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_GREATER_MINES_GOBLIN_HOLDOUT      SkyBlockProfileMemberPlayerDataVisitedZonesInner = "greater_mines_goblin_holdout"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_GREATER_MINES_GOBLIN_UBER_ROOM    SkyBlockProfileMemberPlayerDataVisitedZonesInner = "greater_mines_goblin_uber_room"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_GREATER_MINES_JUNGLE              SkyBlockProfileMemberPlayerDataVisitedZonesInner = "greater_mines_jungle"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_GREATER_MINES_JUNGLE_UBER_ROOM    SkyBlockProfileMemberPlayerDataVisitedZonesInner = "greater_mines_jungle_uber_room"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_GREATER_MINES_MAGMA_FIELDS        SkyBlockProfileMemberPlayerDataVisitedZonesInner = "greater_mines_magma_fields"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_GREATER_MINES_MAGMA_UBER_ROOM     SkyBlockProfileMemberPlayerDataVisitedZonesInner = "greater_mines_magma_uber_room"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_GREATER_MINES_MITHRIL             SkyBlockProfileMemberPlayerDataVisitedZonesInner = "greater_mines_mithril"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_GREATER_MINES_MITHRIL_UBER_ROOM   SkyBlockProfileMemberPlayerDataVisitedZonesInner = "greater_mines_mithril_uber_room"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_GREATER_MINES_PRECURSOR           SkyBlockProfileMemberPlayerDataVisitedZonesInner = "greater_mines_precursor"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_GREATER_MINES_PRECURSOR_UBER_ROOM SkyBlockProfileMemberPlayerDataVisitedZonesInner = "greater_mines_precursor_uber_room"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_HALF_EATEN_CAVE                   SkyBlockProfileMemberPlayerDataVisitedZonesInner = "half_eaten_cave"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_HANGING_COURT                     SkyBlockProfileMemberPlayerDataVisitedZonesInner = "hanging_court"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_HARP_MINIGAME                     SkyBlockProfileMemberPlayerDataVisitedZonesInner = "harp_minigame"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_HERO_BARRACKS                     SkyBlockProfileMemberPlayerDataVisitedZonesInner = "hero_barracks"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_HEX                               SkyBlockProfileMemberPlayerDataVisitedZonesInner = "hex"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_HIGH_LEVEL                        SkyBlockProfileMemberPlayerDataVisitedZonesInner = "high_level"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_HOT_SPRINGS                       SkyBlockProfileMemberPlayerDataVisitedZonesInner = "hot_springs"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_ICE_POND                          SkyBlockProfileMemberPlayerDataVisitedZonesInner = "ice_pond"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_ICE_WALL                          SkyBlockProfileMemberPlayerDataVisitedZonesInner = "ice_wall"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_IGRUPAN_CHICKEN_COOP              SkyBlockProfileMemberPlayerDataVisitedZonesInner = "igrupan_chicken_coop"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_IGRUPAN_HOUSE                     SkyBlockProfileMemberPlayerDataVisitedZonesInner = "igrupan_house"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_INFESTED_HOUSE                    SkyBlockProfileMemberPlayerDataVisitedZonesInner = "infested_house"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_INSIDE_THE_WALL                   SkyBlockProfileMemberPlayerDataVisitedZonesInner = "inside_the_wall"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_INSTANCED                         SkyBlockProfileMemberPlayerDataVisitedZonesInner = "instanced"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_JAKE_HOUSE                        SkyBlockProfileMemberPlayerDataVisitedZonesInner = "jake_house"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_LAGOON_HUT                        SkyBlockProfileMemberPlayerDataVisitedZonesInner = "lagoon_hut"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_LAGOON_PARKOUR                    SkyBlockProfileMemberPlayerDataVisitedZonesInner = "lagoon_parkour"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_LAVA_SPRINGS                      SkyBlockProfileMemberPlayerDataVisitedZonesInner = "lava_springs"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_LEECHES_LAIR                      SkyBlockProfileMemberPlayerDataVisitedZonesInner = "leeches_lair"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_LIBRARY                           SkyBlockProfileMemberPlayerDataVisitedZonesInner = "library"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_LIVING_CAVE                       SkyBlockProfileMemberPlayerDataVisitedZonesInner = "living_cave"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_LIVING_CAVE_2                     SkyBlockProfileMemberPlayerDataVisitedZonesInner = "living_cave_2"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_LONELY_ISLAND                     SkyBlockProfileMemberPlayerDataVisitedZonesInner = "lonely_island"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_LONELY_TERRACE                    SkyBlockProfileMemberPlayerDataVisitedZonesInner = "lonely_terrace"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_MAGE_OUTPOST                      SkyBlockProfileMemberPlayerDataVisitedZonesInner = "mage_outpost"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_MAGMA_CHAMBER                     SkyBlockProfileMemberPlayerDataVisitedZonesInner = "magma_chamber"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_MATRIARCH_LAIR                    SkyBlockProfileMemberPlayerDataVisitedZonesInner = "matriarch_lair"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_MATRIARCH_STOMACH                 SkyBlockProfileMemberPlayerDataVisitedZonesInner = "matriarch_stomach"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_MELANCHOLIC_VIKING                SkyBlockProfileMemberPlayerDataVisitedZonesInner = "melancholic_viking"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_MINE                              SkyBlockProfileMemberPlayerDataVisitedZonesInner = "mine"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_MINERS_GUILD                      SkyBlockProfileMemberPlayerDataVisitedZonesInner = "miners_guild"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_MIRRORVERSE                       SkyBlockProfileMemberPlayerDataVisitedZonesInner = "mirrorverse"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_MOUNT_JERRY                       SkyBlockProfileMemberPlayerDataVisitedZonesInner = "mount_jerry"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_MOUNTAIN                          SkyBlockProfileMemberPlayerDataVisitedZonesInner = "mountain"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_MURDER_HOUSE                      SkyBlockProfileMemberPlayerDataVisitedZonesInner = "murder_house"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_MUSEUM                            SkyBlockProfileMemberPlayerDataVisitedZonesInner = "museum"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_MUSHROOM_DESERT                   SkyBlockProfileMemberPlayerDataVisitedZonesInner = "mushroom_desert"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_MYSTIC_MARSH                      SkyBlockProfileMemberPlayerDataVisitedZonesInner = "mystic_marsh"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_OASIS                             SkyBlockProfileMemberPlayerDataVisitedZonesInner = "oasis"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_ODGER_HUT                         SkyBlockProfileMemberPlayerDataVisitedZonesInner = "odger_hut"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_OVERGROWN_MUSHROOM_CAVE           SkyBlockProfileMemberPlayerDataVisitedZonesInner = "overgrown_mushroom_cave"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_PALACE_BRIDGE                     SkyBlockProfileMemberPlayerDataVisitedZonesInner = "palace_bridge"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_PET_CARE                          SkyBlockProfileMemberPlayerDataVisitedZonesInner = "pet_care"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_PHOTON_PATH                       SkyBlockProfileMemberPlayerDataVisitedZonesInner = "photon_path"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_RABBIT_HOUSE                      SkyBlockProfileMemberPlayerDataVisitedZonesInner = "rabbit_house"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_RAMPART_QUARRY                    SkyBlockProfileMemberPlayerDataVisitedZonesInner = "rampart_quarry"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_REFLECTIVE_POND                   SkyBlockProfileMemberPlayerDataVisitedZonesInner = "reflective_pond"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_REGALIA_ROOM                      SkyBlockProfileMemberPlayerDataVisitedZonesInner = "regalia_room"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_RIFT                              SkyBlockProfileMemberPlayerDataVisitedZonesInner = "rift"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_RIFT_AH                           SkyBlockProfileMemberPlayerDataVisitedZonesInner = "rift_ah"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_RIFT_BASTION                      SkyBlockProfileMemberPlayerDataVisitedZonesInner = "rift_bastion"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_RIFT_CASTLE                       SkyBlockProfileMemberPlayerDataVisitedZonesInner = "rift_castle"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_RIFT_CASTLE_FAIRY_TOWER           SkyBlockProfileMemberPlayerDataVisitedZonesInner = "rift_castle_fairy_tower"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_RIFT_CASTLE_JAIL                  SkyBlockProfileMemberPlayerDataVisitedZonesInner = "rift_castle_jail"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_RIFT_CEREBRAL_CITADEL             SkyBlockProfileMemberPlayerDataVisitedZonesInner = "rift_cerebral_citadel"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_RIFT_COLOSSEUM                    SkyBlockProfileMemberPlayerDataVisitedZonesInner = "rift_colosseum"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_RIFT_COLOSSEUM_AROUND             SkyBlockProfileMemberPlayerDataVisitedZonesInner = "rift_colosseum_around"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_RIFT_GALLERY                      SkyBlockProfileMemberPlayerDataVisitedZonesInner = "rift_gallery"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_RIFT_GALLERY_ENTRANCE             SkyBlockProfileMemberPlayerDataVisitedZonesInner = "rift_gallery_entrance"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_RIFT_MOUNTAIN                     SkyBlockProfileMemberPlayerDataVisitedZonesInner = "rift_mountain"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_RIFT_TIME_CHAMBER                 SkyBlockProfileMemberPlayerDataVisitedZonesInner = "rift_time_chamber"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_RIFT_WATER_PARKOUR                SkyBlockProfileMemberPlayerDataVisitedZonesInner = "rift_water_parkour"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_RIFT_WITHER_CAGE                  SkyBlockProfileMemberPlayerDataVisitedZonesInner = "rift_wither_cage"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_RIFT_WIZARD_TOWER                 SkyBlockProfileMemberPlayerDataVisitedZonesInner = "rift_wizard_tower"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_ROSES_END                         SkyBlockProfileMemberPlayerDataVisitedZonesInner = "roses_end"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_ROYAL_MINES                       SkyBlockProfileMemberPlayerDataVisitedZonesInner = "royal_mines"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_ROYAL_QUARTERS                    SkyBlockProfileMemberPlayerDataVisitedZonesInner = "royal_quarters"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_RUINS                             SkyBlockProfileMemberPlayerDataVisitedZonesInner = "ruins"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_SCARLETON                         SkyBlockProfileMemberPlayerDataVisitedZonesInner = "scarleton"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_SCARLETON_AUCTION_HOUSE           SkyBlockProfileMemberPlayerDataVisitedZonesInner = "scarleton_auction_house"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_SCARLETON_BANK                    SkyBlockProfileMemberPlayerDataVisitedZonesInner = "scarleton_bank"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_SCARLETON_BAZAAR                  SkyBlockProfileMemberPlayerDataVisitedZonesInner = "scarleton_bazaar"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_SCARLETON_BLACKSMITH              SkyBlockProfileMemberPlayerDataVisitedZonesInner = "scarleton_blacksmith"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_SCARLETON_COMMUNITY_CENTER        SkyBlockProfileMemberPlayerDataVisitedZonesInner = "scarleton_community_center"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_SCARLETON_COURTYARD               SkyBlockProfileMemberPlayerDataVisitedZonesInner = "scarleton_courtyard"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_SCARLETON_MAGE_COUNCIL            SkyBlockProfileMemberPlayerDataVisitedZonesInner = "scarleton_mage_council"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_SCARLETON_MINION_SHOP             SkyBlockProfileMemberPlayerDataVisitedZonesInner = "scarleton_minion_shop"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_SCARLETON_PLAZA                   SkyBlockProfileMemberPlayerDataVisitedZonesInner = "scarleton_plaza"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_SCARLETON_THRONE_ROOM             SkyBlockProfileMemberPlayerDataVisitedZonesInner = "scarleton_throne_room"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_SHEN_AUCTION                      SkyBlockProfileMemberPlayerDataVisitedZonesInner = "shen_auction"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_SHEPHERDS_KEEP                    SkyBlockProfileMemberPlayerDataVisitedZonesInner = "shepherds_keep"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_SHERRYS_SHOWROOM                  SkyBlockProfileMemberPlayerDataVisitedZonesInner = "sherrys_showroom"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_SHIFTED_TAVERN                    SkyBlockProfileMemberPlayerDataVisitedZonesInner = "shifted_tavern"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_SMOLDERING_TOMB                   SkyBlockProfileMemberPlayerDataVisitedZonesInner = "smoldering_tomb"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_SPIDER_MOUND                      SkyBlockProfileMemberPlayerDataVisitedZonesInner = "spider_mound"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_SPIDERS_DEN                       SkyBlockProfileMemberPlayerDataVisitedZonesInner = "spiders_den"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_STRONGHOLD                        SkyBlockProfileMemberPlayerDataVisitedZonesInner = "stronghold"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_SUNKEN_ICE_POND                   SkyBlockProfileMemberPlayerDataVisitedZonesInner = "sunken_ice_pond"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_TAILOR                            SkyBlockProfileMemberPlayerDataVisitedZonesInner = "tailor"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_TAVERN                            SkyBlockProfileMemberPlayerDataVisitedZonesInner = "tavern"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_TAYLORS                           SkyBlockProfileMemberPlayerDataVisitedZonesInner = "taylors"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_TERRYS_SHACK                      SkyBlockProfileMemberPlayerDataVisitedZonesInner = "terrys_shack"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_THAUMATURGIST                     SkyBlockProfileMemberPlayerDataVisitedZonesInner = "thaumaturgist"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_THE_BARN                          SkyBlockProfileMemberPlayerDataVisitedZonesInner = "the_barn"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_THE_DUKEDOM                       SkyBlockProfileMemberPlayerDataVisitedZonesInner = "the_dukedom"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_THE_MIST                          SkyBlockProfileMemberPlayerDataVisitedZonesInner = "the_mist"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_TIME_TORN_ISLES                   SkyBlockProfileMemberPlayerDataVisitedZonesInner = "time_torn_isles"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_TRADE_CENTER                      SkyBlockProfileMemberPlayerDataVisitedZonesInner = "trade_center"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_TRAPPERS_DEN_SHOP_AREA            SkyBlockProfileMemberPlayerDataVisitedZonesInner = "trappers_den_shop_area"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_TREASURE_HUNTER_CAMP              SkyBlockProfileMemberPlayerDataVisitedZonesInner = "treasure_hunter_camp"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_UNDERGROUND_LAVA_POOL             SkyBlockProfileMemberPlayerDataVisitedZonesInner = "underground_lava_pool"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_UNINCORPORATED_TERRITORY          SkyBlockProfileMemberPlayerDataVisitedZonesInner = "unincorporated_territory"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_UPPER_MINES                       SkyBlockProfileMemberPlayerDataVisitedZonesInner = "upper_mines"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_VILLAGE                           SkyBlockProfileMemberPlayerDataVisitedZonesInner = "village"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_VILLAGE_PLAZA                     SkyBlockProfileMemberPlayerDataVisitedZonesInner = "village_plaza"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_VOID_SEPULTURE                    SkyBlockProfileMemberPlayerDataVisitedZonesInner = "void_sepulture"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_VOID_SLATE                        SkyBlockProfileMemberPlayerDataVisitedZonesInner = "void_slate"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_WALK_OF_FAME                      SkyBlockProfileMemberPlayerDataVisitedZonesInner = "walk_of_fame"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_WASTELAND                         SkyBlockProfileMemberPlayerDataVisitedZonesInner = "wasteland"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_WEAPONSMITH                       SkyBlockProfileMemberPlayerDataVisitedZonesInner = "weaponsmith"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_WEST_VILLAGE                      SkyBlockProfileMemberPlayerDataVisitedZonesInner = "west_village"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_WILDERNESS                        SkyBlockProfileMemberPlayerDataVisitedZonesInner = "wilderness"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_WINDMILL                          SkyBlockProfileMemberPlayerDataVisitedZonesInner = "windmill"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_WINTER_ISLAND                     SkyBlockProfileMemberPlayerDataVisitedZonesInner = "winter_island"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_WIZARD_TOWER                      SkyBlockProfileMemberPlayerDataVisitedZonesInner = "wizard_tower"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_WIZARDMAN_CHAMBERS                SkyBlockProfileMemberPlayerDataVisitedZonesInner = "wizardman_chambers"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_WIZARDMAN_RACE_TRIAL_GROUNDS      SkyBlockProfileMemberPlayerDataVisitedZonesInner = "wizardman_race_trial_grounds"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_WIZARDMAN_TRIAL_GROUNDS           SkyBlockProfileMemberPlayerDataVisitedZonesInner = "wizardman_trial_grounds"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_WIZARDMAN_VENTS                   SkyBlockProfileMemberPlayerDataVisitedZonesInner = "wizardman_vents"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_WOF_MIRRORVERSE                   SkyBlockProfileMemberPlayerDataVisitedZonesInner = "wof_mirrorverse"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_WOLF_DEN                          SkyBlockProfileMemberPlayerDataVisitedZonesInner = "wolf_den"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_WYLD_PUMPGROTTO                   SkyBlockProfileMemberPlayerDataVisitedZonesInner = "wyld_pumpgrotto"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_WYLD_WOODS                        SkyBlockProfileMemberPlayerDataVisitedZonesInner = "wyld_woods"
	SKYBLOCKPROFILEMEMBERPLAYERDATAVISITEDZONESINNER_ZEALOT_BRUISER_HIDEOUT            SkyBlockProfileMemberPlayerDataVisitedZonesInner = "zealot_bruiser_hideout"
)

// All allowed values of SkyBlockProfileMemberPlayerDataVisitedZonesInner enum
var AllowedSkyBlockProfileMemberPlayerDataVisitedZonesInnerEnumValues = []SkyBlockProfileMemberPlayerDataVisitedZonesInner{
	"abandoned_quarry",
	"arachnes_burrow",
	"arachnes_sanctuary",
	"archaeologist_camp",
	"archery_range",
	"aristocrat_passage",
	"artist_abode",
	"ashfang_ruins",
	"auction_house",
	"aura_laboratory",
	"back_2_basics",
	"backwater_bayou",
	"bank",
	"barbarian_outpost",
	"barry_center",
	"barry_hq",
	"barter_bank",
	"bastion",
	"bazaar_alley",
	"beanstalk",
	"black_lagoon",
	"blacksmith",
	"blazing_fortress",
	"blazing_volcano",
	"bookception",
	"breakable_tnt_wall",
	"builders_house",
	"burning_desert",
	"cake_house",
	"canvas_room",
	"carnival",
	"carts_crafting_co",
	"catacombs_entrance",
	"cathedral",
	"cave_glowing_mushroom",
	"cliffside_veins",
	"colosseum",
	"colosseum_arena",
	"community_center",
	"continuum",
	"crimson_fields",
	"crimson_isle",
	"danger",
	"dark_auction",
	"deep_caverns",
	"deep_caverns_room_1",
	"deep_caverns_room_2",
	"deep_caverns_room_3",
	"deep_caverns_room_4",
	"deep_caverns_room_5",
	"deep_caverns_room_6",
	"deeper_caverns",
	"deeper_caverns_lift",
	"deja_vu_alley",
	"desert_mountain",
	"desert_settlement",
	"divan_gateway",
	"dojo",
	"dojo_arena",
	"dragontail_chief_hut",
	"dragontail_minion_shop",
	"dragontail_town",
	"dragontail_town_auction_house",
	"dragontail_town_bank",
	"dragontail_town_bazaar",
	"dragontail_town_blacksmith",
	"dragontail_town_square",
	"dreadfarm",
	"duel_zone",
	"dungeon",
	"dungeon_hub",
	"dwarven_base_camp",
	"dwarven_tavern",
	"dwarven_village",
	"dynamic_portal_island",
	"einarys_emporium",
	"elder_palace",
	"election_room",
	"enderdragon_boss_room",
	"enderman_sanctuary",
	"enigma",
	"far_reserve",
	"farm",
	"farmhouse",
	"fisherman_hut",
	"fishing_outpost",
	"floating_islands_1",
	"floating_islands_2",
	"floating_islands_3",
	"floating_islands_4",
	"floating_islands_5",
	"flower_house",
	"forest",
	"forge",
	"forge_basin",
	"forgotten_skull",
	"fossil_research_center",
	"garys_shack",
	"gates_mines",
	"glacial_cave",
	"glacite_lake",
	"glacite_tunnels",
	"goblin_burrows",
	"gold_mine",
	"gorge",
	"grand_library",
	"grandmas_house",
	"gravel_mines",
	"greater_mines",
	"greater_mines_crystal_room",
	"greater_mines_fairy_grotto",
	"greater_mines_goblin_holdout",
	"greater_mines_goblin_uber_room",
	"greater_mines_jungle",
	"greater_mines_jungle_uber_room",
	"greater_mines_magma_fields",
	"greater_mines_magma_uber_room",
	"greater_mines_mithril",
	"greater_mines_mithril_uber_room",
	"greater_mines_precursor",
	"greater_mines_precursor_uber_room",
	"half_eaten_cave",
	"hanging_court",
	"harp_minigame",
	"hero_barracks",
	"hex",
	"high_level",
	"hot_springs",
	"ice_pond",
	"ice_wall",
	"igrupan_chicken_coop",
	"igrupan_house",
	"infested_house",
	"inside_the_wall",
	"instanced",
	"jake_house",
	"lagoon_hut",
	"lagoon_parkour",
	"lava_springs",
	"leeches_lair",
	"library",
	"living_cave",
	"living_cave_2",
	"lonely_island",
	"lonely_terrace",
	"mage_outpost",
	"magma_chamber",
	"matriarch_lair",
	"matriarch_stomach",
	"melancholic_viking",
	"mine",
	"miners_guild",
	"mirrorverse",
	"mount_jerry",
	"mountain",
	"murder_house",
	"museum",
	"mushroom_desert",
	"mystic_marsh",
	"oasis",
	"odger_hut",
	"overgrown_mushroom_cave",
	"palace_bridge",
	"pet_care",
	"photon_path",
	"rabbit_house",
	"rampart_quarry",
	"reflective_pond",
	"regalia_room",
	"rift",
	"rift_ah",
	"rift_bastion",
	"rift_castle",
	"rift_castle_fairy_tower",
	"rift_castle_jail",
	"rift_cerebral_citadel",
	"rift_colosseum",
	"rift_colosseum_around",
	"rift_gallery",
	"rift_gallery_entrance",
	"rift_mountain",
	"rift_time_chamber",
	"rift_water_parkour",
	"rift_wither_cage",
	"rift_wizard_tower",
	"roses_end",
	"royal_mines",
	"royal_quarters",
	"ruins",
	"scarleton",
	"scarleton_auction_house",
	"scarleton_bank",
	"scarleton_bazaar",
	"scarleton_blacksmith",
	"scarleton_community_center",
	"scarleton_courtyard",
	"scarleton_mage_council",
	"scarleton_minion_shop",
	"scarleton_plaza",
	"scarleton_throne_room",
	"shen_auction",
	"shepherds_keep",
	"sherrys_showroom",
	"shifted_tavern",
	"smoldering_tomb",
	"spider_mound",
	"spiders_den",
	"stronghold",
	"sunken_ice_pond",
	"tailor",
	"tavern",
	"taylors",
	"terrys_shack",
	"thaumaturgist",
	"the_barn",
	"the_dukedom",
	"the_mist",
	"time_torn_isles",
	"trade_center",
	"trappers_den_shop_area",
	"treasure_hunter_camp",
	"underground_lava_pool",
	"unincorporated_territory",
	"upper_mines",
	"village",
	"village_plaza",
	"void_sepulture",
	"void_slate",
	"walk_of_fame",
	"wasteland",
	"weaponsmith",
	"west_village",
	"wilderness",
	"windmill",
	"winter_island",
	"wizard_tower",
	"wizardman_chambers",
	"wizardman_race_trial_grounds",
	"wizardman_trial_grounds",
	"wizardman_vents",
	"wof_mirrorverse",
	"wolf_den",
	"wyld_pumpgrotto",
	"wyld_woods",
	"zealot_bruiser_hideout",
}

func (v *SkyBlockProfileMemberPlayerDataVisitedZonesInner) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SkyBlockProfileMemberPlayerDataVisitedZonesInner(value)
	for _, existing := range AllowedSkyBlockProfileMemberPlayerDataVisitedZonesInnerEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid SkyBlockProfileMemberPlayerDataVisitedZonesInner", value)
}

// NewSkyBlockProfileMemberPlayerDataVisitedZonesInnerFromValue returns a pointer to a valid SkyBlockProfileMemberPlayerDataVisitedZonesInner
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSkyBlockProfileMemberPlayerDataVisitedZonesInnerFromValue(v string) (*SkyBlockProfileMemberPlayerDataVisitedZonesInner, error) {
	ev := SkyBlockProfileMemberPlayerDataVisitedZonesInner(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for SkyBlockProfileMemberPlayerDataVisitedZonesInner: valid values are %v", v, AllowedSkyBlockProfileMemberPlayerDataVisitedZonesInnerEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v SkyBlockProfileMemberPlayerDataVisitedZonesInner) IsValid() bool {
	for _, existing := range AllowedSkyBlockProfileMemberPlayerDataVisitedZonesInnerEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to SkyBlockProfileMemberPlayerData_visited_zones_inner value
func (v SkyBlockProfileMemberPlayerDataVisitedZonesInner) Ptr() *SkyBlockProfileMemberPlayerDataVisitedZonesInner {
	return &v
}

type NullableSkyBlockProfileMemberPlayerDataVisitedZonesInner struct {
	value *SkyBlockProfileMemberPlayerDataVisitedZonesInner
	isSet bool
}

func (v NullableSkyBlockProfileMemberPlayerDataVisitedZonesInner) Get() *SkyBlockProfileMemberPlayerDataVisitedZonesInner {
	return v.value
}

func (v *NullableSkyBlockProfileMemberPlayerDataVisitedZonesInner) Set(val *SkyBlockProfileMemberPlayerDataVisitedZonesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableSkyBlockProfileMemberPlayerDataVisitedZonesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableSkyBlockProfileMemberPlayerDataVisitedZonesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSkyBlockProfileMemberPlayerDataVisitedZonesInner(val *SkyBlockProfileMemberPlayerDataVisitedZonesInner) *NullableSkyBlockProfileMemberPlayerDataVisitedZonesInner {
	return &NullableSkyBlockProfileMemberPlayerDataVisitedZonesInner{value: val, isSet: true}
}

func (v NullableSkyBlockProfileMemberPlayerDataVisitedZonesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSkyBlockProfileMemberPlayerDataVisitedZonesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
