/*
Hypixel Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the V2SkyblockBingoGet200ResponseEventsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V2SkyblockBingoGet200ResponseEventsInner{}

// V2SkyblockBingoGet200ResponseEventsInner struct for V2SkyblockBingoGet200ResponseEventsInner
type V2SkyblockBingoGet200ResponseEventsInner struct {
	// The completed goal IDs
	CompletedGoals []string `json:"completed_goals"`
	// The id for this event
	Key int64 `json:"key"`
	// The amount of points earned
	Points int64 `json:"points"`
}

type _V2SkyblockBingoGet200ResponseEventsInner V2SkyblockBingoGet200ResponseEventsInner

// NewV2SkyblockBingoGet200ResponseEventsInner instantiates a new V2SkyblockBingoGet200ResponseEventsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2SkyblockBingoGet200ResponseEventsInner(completedGoals []string, key int64, points int64) *V2SkyblockBingoGet200ResponseEventsInner {
	this := V2SkyblockBingoGet200ResponseEventsInner{}
	this.CompletedGoals = completedGoals
	this.Key = key
	this.Points = points
	return &this
}

// NewV2SkyblockBingoGet200ResponseEventsInnerWithDefaults instantiates a new V2SkyblockBingoGet200ResponseEventsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2SkyblockBingoGet200ResponseEventsInnerWithDefaults() *V2SkyblockBingoGet200ResponseEventsInner {
	this := V2SkyblockBingoGet200ResponseEventsInner{}
	return &this
}

// GetCompletedGoals returns the CompletedGoals field value
func (o *V2SkyblockBingoGet200ResponseEventsInner) GetCompletedGoals() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.CompletedGoals
}

// GetCompletedGoalsOk returns a tuple with the CompletedGoals field value
// and a boolean to check if the value has been set.
func (o *V2SkyblockBingoGet200ResponseEventsInner) GetCompletedGoalsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CompletedGoals, true
}

// SetCompletedGoals sets field value
func (o *V2SkyblockBingoGet200ResponseEventsInner) SetCompletedGoals(v []string) {
	o.CompletedGoals = v
}

// GetKey returns the Key field value
func (o *V2SkyblockBingoGet200ResponseEventsInner) GetKey() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *V2SkyblockBingoGet200ResponseEventsInner) GetKeyOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *V2SkyblockBingoGet200ResponseEventsInner) SetKey(v int64) {
	o.Key = v
}

// GetPoints returns the Points field value
func (o *V2SkyblockBingoGet200ResponseEventsInner) GetPoints() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Points
}

// GetPointsOk returns a tuple with the Points field value
// and a boolean to check if the value has been set.
func (o *V2SkyblockBingoGet200ResponseEventsInner) GetPointsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Points, true
}

// SetPoints sets field value
func (o *V2SkyblockBingoGet200ResponseEventsInner) SetPoints(v int64) {
	o.Points = v
}

func (o V2SkyblockBingoGet200ResponseEventsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V2SkyblockBingoGet200ResponseEventsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["completed_goals"] = o.CompletedGoals
	toSerialize["key"] = o.Key
	toSerialize["points"] = o.Points
	return toSerialize, nil
}

func (o *V2SkyblockBingoGet200ResponseEventsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"completed_goals",
		"key",
		"points",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV2SkyblockBingoGet200ResponseEventsInner := _V2SkyblockBingoGet200ResponseEventsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV2SkyblockBingoGet200ResponseEventsInner)

	if err != nil {
		return err
	}

	*o = V2SkyblockBingoGet200ResponseEventsInner(varV2SkyblockBingoGet200ResponseEventsInner)

	return err
}

type NullableV2SkyblockBingoGet200ResponseEventsInner struct {
	value *V2SkyblockBingoGet200ResponseEventsInner
	isSet bool
}

func (v NullableV2SkyblockBingoGet200ResponseEventsInner) Get() *V2SkyblockBingoGet200ResponseEventsInner {
	return v.value
}

func (v *NullableV2SkyblockBingoGet200ResponseEventsInner) Set(val *V2SkyblockBingoGet200ResponseEventsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableV2SkyblockBingoGet200ResponseEventsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableV2SkyblockBingoGet200ResponseEventsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2SkyblockBingoGet200ResponseEventsInner(val *V2SkyblockBingoGet200ResponseEventsInner) *NullableV2SkyblockBingoGet200ResponseEventsInner {
	return &NullableV2SkyblockBingoGet200ResponseEventsInner{value: val, isSet: true}
}

func (v NullableV2SkyblockBingoGet200ResponseEventsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2SkyblockBingoGet200ResponseEventsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
