/*
Hypixel Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// SkyBlockProfileMemberMiningCoreBiomesPrecursorPartsDeliveredInner the model 'SkyBlockProfileMemberMiningCoreBiomesPrecursorPartsDeliveredInner'
type SkyBlockProfileMemberMiningCoreBiomesPrecursorPartsDeliveredInner string

// List of SkyBlockProfileMemberMiningCoreBiomesPrecursor_parts_delivered_inner
const (
	SKYBLOCKPROFILEMEMBERMININGCOREBIOMESPRECURSORPARTSDELIVEREDINNER_CONTROL_SWITCH       SkyBlockProfileMemberMiningCoreBiomesPrecursorPartsDeliveredInner = "CONTROL_SWITCH"
	SKYBLOCKPROFILEMEMBERMININGCOREBIOMESPRECURSORPARTSDELIVEREDINNER_ELECTRON_TRANSMITTER SkyBlockProfileMemberMiningCoreBiomesPrecursorPartsDeliveredInner = "ELECTRON_TRANSMITTER"
	SKYBLOCKPROFILEMEMBERMININGCOREBIOMESPRECURSORPARTSDELIVEREDINNER_FTX_3070             SkyBlockProfileMemberMiningCoreBiomesPrecursorPartsDeliveredInner = "FTX_3070"
	SKYBLOCKPROFILEMEMBERMININGCOREBIOMESPRECURSORPARTSDELIVEREDINNER_ROBOTRON_REFLECTOR   SkyBlockProfileMemberMiningCoreBiomesPrecursorPartsDeliveredInner = "ROBOTRON_REFLECTOR"
	SKYBLOCKPROFILEMEMBERMININGCOREBIOMESPRECURSORPARTSDELIVEREDINNER_SUPERLITE_MOTOR      SkyBlockProfileMemberMiningCoreBiomesPrecursorPartsDeliveredInner = "SUPERLITE_MOTOR"
	SKYBLOCKPROFILEMEMBERMININGCOREBIOMESPRECURSORPARTSDELIVEREDINNER_SYNTHETIC_HEART      SkyBlockProfileMemberMiningCoreBiomesPrecursorPartsDeliveredInner = "SYNTHETIC_HEART"
)

// All allowed values of SkyBlockProfileMemberMiningCoreBiomesPrecursorPartsDeliveredInner enum
var AllowedSkyBlockProfileMemberMiningCoreBiomesPrecursorPartsDeliveredInnerEnumValues = []SkyBlockProfileMemberMiningCoreBiomesPrecursorPartsDeliveredInner{
	"CONTROL_SWITCH",
	"ELECTRON_TRANSMITTER",
	"FTX_3070",
	"ROBOTRON_REFLECTOR",
	"SUPERLITE_MOTOR",
	"SYNTHETIC_HEART",
}

func (v *SkyBlockProfileMemberMiningCoreBiomesPrecursorPartsDeliveredInner) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SkyBlockProfileMemberMiningCoreBiomesPrecursorPartsDeliveredInner(value)
	for _, existing := range AllowedSkyBlockProfileMemberMiningCoreBiomesPrecursorPartsDeliveredInnerEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid SkyBlockProfileMemberMiningCoreBiomesPrecursorPartsDeliveredInner", value)
}

// NewSkyBlockProfileMemberMiningCoreBiomesPrecursorPartsDeliveredInnerFromValue returns a pointer to a valid SkyBlockProfileMemberMiningCoreBiomesPrecursorPartsDeliveredInner
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSkyBlockProfileMemberMiningCoreBiomesPrecursorPartsDeliveredInnerFromValue(v string) (*SkyBlockProfileMemberMiningCoreBiomesPrecursorPartsDeliveredInner, error) {
	ev := SkyBlockProfileMemberMiningCoreBiomesPrecursorPartsDeliveredInner(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for SkyBlockProfileMemberMiningCoreBiomesPrecursorPartsDeliveredInner: valid values are %v", v, AllowedSkyBlockProfileMemberMiningCoreBiomesPrecursorPartsDeliveredInnerEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v SkyBlockProfileMemberMiningCoreBiomesPrecursorPartsDeliveredInner) IsValid() bool {
	for _, existing := range AllowedSkyBlockProfileMemberMiningCoreBiomesPrecursorPartsDeliveredInnerEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to SkyBlockProfileMemberMiningCoreBiomesPrecursor_parts_delivered_inner value
func (v SkyBlockProfileMemberMiningCoreBiomesPrecursorPartsDeliveredInner) Ptr() *SkyBlockProfileMemberMiningCoreBiomesPrecursorPartsDeliveredInner {
	return &v
}

type NullableSkyBlockProfileMemberMiningCoreBiomesPrecursorPartsDeliveredInner struct {
	value *SkyBlockProfileMemberMiningCoreBiomesPrecursorPartsDeliveredInner
	isSet bool
}

func (v NullableSkyBlockProfileMemberMiningCoreBiomesPrecursorPartsDeliveredInner) Get() *SkyBlockProfileMemberMiningCoreBiomesPrecursorPartsDeliveredInner {
	return v.value
}

func (v *NullableSkyBlockProfileMemberMiningCoreBiomesPrecursorPartsDeliveredInner) Set(val *SkyBlockProfileMemberMiningCoreBiomesPrecursorPartsDeliveredInner) {
	v.value = val
	v.isSet = true
}

func (v NullableSkyBlockProfileMemberMiningCoreBiomesPrecursorPartsDeliveredInner) IsSet() bool {
	return v.isSet
}

func (v *NullableSkyBlockProfileMemberMiningCoreBiomesPrecursorPartsDeliveredInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSkyBlockProfileMemberMiningCoreBiomesPrecursorPartsDeliveredInner(val *SkyBlockProfileMemberMiningCoreBiomesPrecursorPartsDeliveredInner) *NullableSkyBlockProfileMemberMiningCoreBiomesPrecursorPartsDeliveredInner {
	return &NullableSkyBlockProfileMemberMiningCoreBiomesPrecursorPartsDeliveredInner{value: val, isSet: true}
}

func (v NullableSkyBlockProfileMemberMiningCoreBiomesPrecursorPartsDeliveredInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSkyBlockProfileMemberMiningCoreBiomesPrecursorPartsDeliveredInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
