/*
Hypixel Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SkyBlockProfileMemberDungeonsTreasures type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SkyBlockProfileMemberDungeonsTreasures{}

// SkyBlockProfileMemberDungeonsTreasures struct for SkyBlockProfileMemberDungeonsTreasures
type SkyBlockProfileMemberDungeonsTreasures struct {
	Chests []SkyBlockProfileMemberDungeonsTreasuresChest `json:"chests,omitempty"`
	Runs   []SkyBlockProfileMemberDungeonsTreasuresRun   `json:"runs,omitempty"`
}

// NewSkyBlockProfileMemberDungeonsTreasures instantiates a new SkyBlockProfileMemberDungeonsTreasures object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSkyBlockProfileMemberDungeonsTreasures() *SkyBlockProfileMemberDungeonsTreasures {
	this := SkyBlockProfileMemberDungeonsTreasures{}
	return &this
}

// NewSkyBlockProfileMemberDungeonsTreasuresWithDefaults instantiates a new SkyBlockProfileMemberDungeonsTreasures object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSkyBlockProfileMemberDungeonsTreasuresWithDefaults() *SkyBlockProfileMemberDungeonsTreasures {
	this := SkyBlockProfileMemberDungeonsTreasures{}
	return &this
}

// GetChests returns the Chests field value if set, zero value otherwise.
func (o *SkyBlockProfileMemberDungeonsTreasures) GetChests() []SkyBlockProfileMemberDungeonsTreasuresChest {
	if o == nil || IsNil(o.Chests) {
		var ret []SkyBlockProfileMemberDungeonsTreasuresChest
		return ret
	}
	return o.Chests
}

// GetChestsOk returns a tuple with the Chests field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SkyBlockProfileMemberDungeonsTreasures) GetChestsOk() ([]SkyBlockProfileMemberDungeonsTreasuresChest, bool) {
	if o == nil || IsNil(o.Chests) {
		return nil, false
	}
	return o.Chests, true
}

// HasChests returns a boolean if a field has been set.
func (o *SkyBlockProfileMemberDungeonsTreasures) HasChests() bool {
	if o != nil && !IsNil(o.Chests) {
		return true
	}

	return false
}

// SetChests gets a reference to the given []SkyBlockProfileMemberDungeonsTreasuresChest and assigns it to the Chests field.
func (o *SkyBlockProfileMemberDungeonsTreasures) SetChests(v []SkyBlockProfileMemberDungeonsTreasuresChest) {
	o.Chests = v
}

// GetRuns returns the Runs field value if set, zero value otherwise.
func (o *SkyBlockProfileMemberDungeonsTreasures) GetRuns() []SkyBlockProfileMemberDungeonsTreasuresRun {
	if o == nil || IsNil(o.Runs) {
		var ret []SkyBlockProfileMemberDungeonsTreasuresRun
		return ret
	}
	return o.Runs
}

// GetRunsOk returns a tuple with the Runs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SkyBlockProfileMemberDungeonsTreasures) GetRunsOk() ([]SkyBlockProfileMemberDungeonsTreasuresRun, bool) {
	if o == nil || IsNil(o.Runs) {
		return nil, false
	}
	return o.Runs, true
}

// HasRuns returns a boolean if a field has been set.
func (o *SkyBlockProfileMemberDungeonsTreasures) HasRuns() bool {
	if o != nil && !IsNil(o.Runs) {
		return true
	}

	return false
}

// SetRuns gets a reference to the given []SkyBlockProfileMemberDungeonsTreasuresRun and assigns it to the Runs field.
func (o *SkyBlockProfileMemberDungeonsTreasures) SetRuns(v []SkyBlockProfileMemberDungeonsTreasuresRun) {
	o.Runs = v
}

func (o SkyBlockProfileMemberDungeonsTreasures) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SkyBlockProfileMemberDungeonsTreasures) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Chests) {
		toSerialize["chests"] = o.Chests
	}
	if !IsNil(o.Runs) {
		toSerialize["runs"] = o.Runs
	}
	return toSerialize, nil
}

type NullableSkyBlockProfileMemberDungeonsTreasures struct {
	value *SkyBlockProfileMemberDungeonsTreasures
	isSet bool
}

func (v NullableSkyBlockProfileMemberDungeonsTreasures) Get() *SkyBlockProfileMemberDungeonsTreasures {
	return v.value
}

func (v *NullableSkyBlockProfileMemberDungeonsTreasures) Set(val *SkyBlockProfileMemberDungeonsTreasures) {
	v.value = val
	v.isSet = true
}

func (v NullableSkyBlockProfileMemberDungeonsTreasures) IsSet() bool {
	return v.isSet
}

func (v *NullableSkyBlockProfileMemberDungeonsTreasures) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSkyBlockProfileMemberDungeonsTreasures(val *SkyBlockProfileMemberDungeonsTreasures) *NullableSkyBlockProfileMemberDungeonsTreasures {
	return &NullableSkyBlockProfileMemberDungeonsTreasures{value: val, isSet: true}
}

func (v NullableSkyBlockProfileMemberDungeonsTreasures) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSkyBlockProfileMemberDungeonsTreasures) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
