/*
Hypixel Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SkyBlockProfileMemberMiningCore type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SkyBlockProfileMemberMiningCore{}

// SkyBlockProfileMemberMiningCore struct for SkyBlockProfileMemberMiningCore
type SkyBlockProfileMemberMiningCore struct {
	Biomes                      SkyBlockProfileMemberMiningCoreBiomes   `json:"biomes"`
	Crystals                    SkyBlockProfileMemberMiningCoreCrystals `json:"crystals"`
	DailyOresMined              int64                                   `json:"daily_ores_mined"`
	DailyOresMinedDay           int64                                   `json:"daily_ores_mined_day"`
	DailyOresMinedDayGemstone   int64                                   `json:"daily_ores_mined_day_gemstone"`
	DailyOresMinedDayGlacite    int64                                   `json:"daily_ores_mined_day_glacite"`
	DailyOresMinedDayMithrilOre int64                                   `json:"daily_ores_mined_day_mithril_ore"`
	DailyOresMinedGemstone      int64                                   `json:"daily_ores_mined_gemstone"`
	DailyOresMinedGlacite       int64                                   `json:"daily_ores_mined_glacite"`
	DailyOresMinedMithrilOre    int64                                   `json:"daily_ores_mined_mithril_ore"`
	Experience                  int64                                   `json:"experience"`
	GreaterMinesLastAccess      int64                                   `json:"greater_mines_last_access"`
	LastReset                   int64                                   `json:"last_reset"`
	Nodes                       SkyBlockProfileMemberMiningCoreNodes    `json:"nodes"`
	PowderGemstone              int64                                   `json:"powder_gemstone"`
	PowderGemstoneTotal         int64                                   `json:"powder_gemstone_total"`
	PowderGlacite               int64                                   `json:"powder_glacite"`
	PowderGlaciteTotal          int64                                   `json:"powder_glacite_total"`
	PowderMithril               int64                                   `json:"powder_mithril"`
	PowderMithrilTotal          int64                                   `json:"powder_mithril_total"`
	PowderSpentGemstone         int64                                   `json:"powder_spent_gemstone"`
	PowderSpentGlacite          int64                                   `json:"powder_spent_glacite"`
	PowderSpentMithril          int64                                   `json:"powder_spent_mithril"`
	ReceivedFreeTier            bool                                    `json:"received_free_tier"`
	RetroactiveTier2Token       bool                                    `json:"retroactive_tier2_token"`
	TokensSpent                 int64                                   `json:"tokens_spent"`
}

type _SkyBlockProfileMemberMiningCore SkyBlockProfileMemberMiningCore

// NewSkyBlockProfileMemberMiningCore instantiates a new SkyBlockProfileMemberMiningCore object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSkyBlockProfileMemberMiningCore(biomes SkyBlockProfileMemberMiningCoreBiomes, crystals SkyBlockProfileMemberMiningCoreCrystals, dailyOresMined int64, dailyOresMinedDay int64, dailyOresMinedDayGemstone int64, dailyOresMinedDayGlacite int64, dailyOresMinedDayMithrilOre int64, dailyOresMinedGemstone int64, dailyOresMinedGlacite int64, dailyOresMinedMithrilOre int64, experience int64, greaterMinesLastAccess int64, lastReset int64, nodes SkyBlockProfileMemberMiningCoreNodes, powderGemstone int64, powderGemstoneTotal int64, powderGlacite int64, powderGlaciteTotal int64, powderMithril int64, powderMithrilTotal int64, powderSpentGemstone int64, powderSpentGlacite int64, powderSpentMithril int64, receivedFreeTier bool, retroactiveTier2Token bool, tokensSpent int64) *SkyBlockProfileMemberMiningCore {
	this := SkyBlockProfileMemberMiningCore{}
	this.Biomes = biomes
	this.Crystals = crystals
	this.DailyOresMined = dailyOresMined
	this.DailyOresMinedDay = dailyOresMinedDay
	this.DailyOresMinedDayGemstone = dailyOresMinedDayGemstone
	this.DailyOresMinedDayGlacite = dailyOresMinedDayGlacite
	this.DailyOresMinedDayMithrilOre = dailyOresMinedDayMithrilOre
	this.DailyOresMinedGemstone = dailyOresMinedGemstone
	this.DailyOresMinedGlacite = dailyOresMinedGlacite
	this.DailyOresMinedMithrilOre = dailyOresMinedMithrilOre
	this.Experience = experience
	this.GreaterMinesLastAccess = greaterMinesLastAccess
	this.LastReset = lastReset
	this.Nodes = nodes
	this.PowderGemstone = powderGemstone
	this.PowderGemstoneTotal = powderGemstoneTotal
	this.PowderGlacite = powderGlacite
	this.PowderGlaciteTotal = powderGlaciteTotal
	this.PowderMithril = powderMithril
	this.PowderMithrilTotal = powderMithrilTotal
	this.PowderSpentGemstone = powderSpentGemstone
	this.PowderSpentGlacite = powderSpentGlacite
	this.PowderSpentMithril = powderSpentMithril
	this.ReceivedFreeTier = receivedFreeTier
	this.RetroactiveTier2Token = retroactiveTier2Token
	this.TokensSpent = tokensSpent
	return &this
}

// NewSkyBlockProfileMemberMiningCoreWithDefaults instantiates a new SkyBlockProfileMemberMiningCore object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSkyBlockProfileMemberMiningCoreWithDefaults() *SkyBlockProfileMemberMiningCore {
	this := SkyBlockProfileMemberMiningCore{}
	return &this
}

// GetBiomes returns the Biomes field value
func (o *SkyBlockProfileMemberMiningCore) GetBiomes() SkyBlockProfileMemberMiningCoreBiomes {
	if o == nil {
		var ret SkyBlockProfileMemberMiningCoreBiomes
		return ret
	}

	return o.Biomes
}

// GetBiomesOk returns a tuple with the Biomes field value
// and a boolean to check if the value has been set.
func (o *SkyBlockProfileMemberMiningCore) GetBiomesOk() (*SkyBlockProfileMemberMiningCoreBiomes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Biomes, true
}

// SetBiomes sets field value
func (o *SkyBlockProfileMemberMiningCore) SetBiomes(v SkyBlockProfileMemberMiningCoreBiomes) {
	o.Biomes = v
}

// GetCrystals returns the Crystals field value
func (o *SkyBlockProfileMemberMiningCore) GetCrystals() SkyBlockProfileMemberMiningCoreCrystals {
	if o == nil {
		var ret SkyBlockProfileMemberMiningCoreCrystals
		return ret
	}

	return o.Crystals
}

// GetCrystalsOk returns a tuple with the Crystals field value
// and a boolean to check if the value has been set.
func (o *SkyBlockProfileMemberMiningCore) GetCrystalsOk() (*SkyBlockProfileMemberMiningCoreCrystals, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Crystals, true
}

// SetCrystals sets field value
func (o *SkyBlockProfileMemberMiningCore) SetCrystals(v SkyBlockProfileMemberMiningCoreCrystals) {
	o.Crystals = v
}

// GetDailyOresMined returns the DailyOresMined field value
func (o *SkyBlockProfileMemberMiningCore) GetDailyOresMined() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.DailyOresMined
}

// GetDailyOresMinedOk returns a tuple with the DailyOresMined field value
// and a boolean to check if the value has been set.
func (o *SkyBlockProfileMemberMiningCore) GetDailyOresMinedOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DailyOresMined, true
}

// SetDailyOresMined sets field value
func (o *SkyBlockProfileMemberMiningCore) SetDailyOresMined(v int64) {
	o.DailyOresMined = v
}

// GetDailyOresMinedDay returns the DailyOresMinedDay field value
func (o *SkyBlockProfileMemberMiningCore) GetDailyOresMinedDay() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.DailyOresMinedDay
}

// GetDailyOresMinedDayOk returns a tuple with the DailyOresMinedDay field value
// and a boolean to check if the value has been set.
func (o *SkyBlockProfileMemberMiningCore) GetDailyOresMinedDayOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DailyOresMinedDay, true
}

// SetDailyOresMinedDay sets field value
func (o *SkyBlockProfileMemberMiningCore) SetDailyOresMinedDay(v int64) {
	o.DailyOresMinedDay = v
}

// GetDailyOresMinedDayGemstone returns the DailyOresMinedDayGemstone field value
func (o *SkyBlockProfileMemberMiningCore) GetDailyOresMinedDayGemstone() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.DailyOresMinedDayGemstone
}

// GetDailyOresMinedDayGemstoneOk returns a tuple with the DailyOresMinedDayGemstone field value
// and a boolean to check if the value has been set.
func (o *SkyBlockProfileMemberMiningCore) GetDailyOresMinedDayGemstoneOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DailyOresMinedDayGemstone, true
}

// SetDailyOresMinedDayGemstone sets field value
func (o *SkyBlockProfileMemberMiningCore) SetDailyOresMinedDayGemstone(v int64) {
	o.DailyOresMinedDayGemstone = v
}

// GetDailyOresMinedDayGlacite returns the DailyOresMinedDayGlacite field value
func (o *SkyBlockProfileMemberMiningCore) GetDailyOresMinedDayGlacite() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.DailyOresMinedDayGlacite
}

// GetDailyOresMinedDayGlaciteOk returns a tuple with the DailyOresMinedDayGlacite field value
// and a boolean to check if the value has been set.
func (o *SkyBlockProfileMemberMiningCore) GetDailyOresMinedDayGlaciteOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DailyOresMinedDayGlacite, true
}

// SetDailyOresMinedDayGlacite sets field value
func (o *SkyBlockProfileMemberMiningCore) SetDailyOresMinedDayGlacite(v int64) {
	o.DailyOresMinedDayGlacite = v
}

// GetDailyOresMinedDayMithrilOre returns the DailyOresMinedDayMithrilOre field value
func (o *SkyBlockProfileMemberMiningCore) GetDailyOresMinedDayMithrilOre() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.DailyOresMinedDayMithrilOre
}

// GetDailyOresMinedDayMithrilOreOk returns a tuple with the DailyOresMinedDayMithrilOre field value
// and a boolean to check if the value has been set.
func (o *SkyBlockProfileMemberMiningCore) GetDailyOresMinedDayMithrilOreOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DailyOresMinedDayMithrilOre, true
}

// SetDailyOresMinedDayMithrilOre sets field value
func (o *SkyBlockProfileMemberMiningCore) SetDailyOresMinedDayMithrilOre(v int64) {
	o.DailyOresMinedDayMithrilOre = v
}

// GetDailyOresMinedGemstone returns the DailyOresMinedGemstone field value
func (o *SkyBlockProfileMemberMiningCore) GetDailyOresMinedGemstone() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.DailyOresMinedGemstone
}

// GetDailyOresMinedGemstoneOk returns a tuple with the DailyOresMinedGemstone field value
// and a boolean to check if the value has been set.
func (o *SkyBlockProfileMemberMiningCore) GetDailyOresMinedGemstoneOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DailyOresMinedGemstone, true
}

// SetDailyOresMinedGemstone sets field value
func (o *SkyBlockProfileMemberMiningCore) SetDailyOresMinedGemstone(v int64) {
	o.DailyOresMinedGemstone = v
}

// GetDailyOresMinedGlacite returns the DailyOresMinedGlacite field value
func (o *SkyBlockProfileMemberMiningCore) GetDailyOresMinedGlacite() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.DailyOresMinedGlacite
}

// GetDailyOresMinedGlaciteOk returns a tuple with the DailyOresMinedGlacite field value
// and a boolean to check if the value has been set.
func (o *SkyBlockProfileMemberMiningCore) GetDailyOresMinedGlaciteOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DailyOresMinedGlacite, true
}

// SetDailyOresMinedGlacite sets field value
func (o *SkyBlockProfileMemberMiningCore) SetDailyOresMinedGlacite(v int64) {
	o.DailyOresMinedGlacite = v
}

// GetDailyOresMinedMithrilOre returns the DailyOresMinedMithrilOre field value
func (o *SkyBlockProfileMemberMiningCore) GetDailyOresMinedMithrilOre() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.DailyOresMinedMithrilOre
}

// GetDailyOresMinedMithrilOreOk returns a tuple with the DailyOresMinedMithrilOre field value
// and a boolean to check if the value has been set.
func (o *SkyBlockProfileMemberMiningCore) GetDailyOresMinedMithrilOreOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DailyOresMinedMithrilOre, true
}

// SetDailyOresMinedMithrilOre sets field value
func (o *SkyBlockProfileMemberMiningCore) SetDailyOresMinedMithrilOre(v int64) {
	o.DailyOresMinedMithrilOre = v
}

// GetExperience returns the Experience field value
func (o *SkyBlockProfileMemberMiningCore) GetExperience() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Experience
}

// GetExperienceOk returns a tuple with the Experience field value
// and a boolean to check if the value has been set.
func (o *SkyBlockProfileMemberMiningCore) GetExperienceOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Experience, true
}

// SetExperience sets field value
func (o *SkyBlockProfileMemberMiningCore) SetExperience(v int64) {
	o.Experience = v
}

// GetGreaterMinesLastAccess returns the GreaterMinesLastAccess field value
func (o *SkyBlockProfileMemberMiningCore) GetGreaterMinesLastAccess() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.GreaterMinesLastAccess
}

// GetGreaterMinesLastAccessOk returns a tuple with the GreaterMinesLastAccess field value
// and a boolean to check if the value has been set.
func (o *SkyBlockProfileMemberMiningCore) GetGreaterMinesLastAccessOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GreaterMinesLastAccess, true
}

// SetGreaterMinesLastAccess sets field value
func (o *SkyBlockProfileMemberMiningCore) SetGreaterMinesLastAccess(v int64) {
	o.GreaterMinesLastAccess = v
}

// GetLastReset returns the LastReset field value
func (o *SkyBlockProfileMemberMiningCore) GetLastReset() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.LastReset
}

// GetLastResetOk returns a tuple with the LastReset field value
// and a boolean to check if the value has been set.
func (o *SkyBlockProfileMemberMiningCore) GetLastResetOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastReset, true
}

// SetLastReset sets field value
func (o *SkyBlockProfileMemberMiningCore) SetLastReset(v int64) {
	o.LastReset = v
}

// GetNodes returns the Nodes field value
func (o *SkyBlockProfileMemberMiningCore) GetNodes() SkyBlockProfileMemberMiningCoreNodes {
	if o == nil {
		var ret SkyBlockProfileMemberMiningCoreNodes
		return ret
	}

	return o.Nodes
}

// GetNodesOk returns a tuple with the Nodes field value
// and a boolean to check if the value has been set.
func (o *SkyBlockProfileMemberMiningCore) GetNodesOk() (*SkyBlockProfileMemberMiningCoreNodes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Nodes, true
}

// SetNodes sets field value
func (o *SkyBlockProfileMemberMiningCore) SetNodes(v SkyBlockProfileMemberMiningCoreNodes) {
	o.Nodes = v
}

// GetPowderGemstone returns the PowderGemstone field value
func (o *SkyBlockProfileMemberMiningCore) GetPowderGemstone() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.PowderGemstone
}

// GetPowderGemstoneOk returns a tuple with the PowderGemstone field value
// and a boolean to check if the value has been set.
func (o *SkyBlockProfileMemberMiningCore) GetPowderGemstoneOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PowderGemstone, true
}

// SetPowderGemstone sets field value
func (o *SkyBlockProfileMemberMiningCore) SetPowderGemstone(v int64) {
	o.PowderGemstone = v
}

// GetPowderGemstoneTotal returns the PowderGemstoneTotal field value
func (o *SkyBlockProfileMemberMiningCore) GetPowderGemstoneTotal() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.PowderGemstoneTotal
}

// GetPowderGemstoneTotalOk returns a tuple with the PowderGemstoneTotal field value
// and a boolean to check if the value has been set.
func (o *SkyBlockProfileMemberMiningCore) GetPowderGemstoneTotalOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PowderGemstoneTotal, true
}

// SetPowderGemstoneTotal sets field value
func (o *SkyBlockProfileMemberMiningCore) SetPowderGemstoneTotal(v int64) {
	o.PowderGemstoneTotal = v
}

// GetPowderGlacite returns the PowderGlacite field value
func (o *SkyBlockProfileMemberMiningCore) GetPowderGlacite() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.PowderGlacite
}

// GetPowderGlaciteOk returns a tuple with the PowderGlacite field value
// and a boolean to check if the value has been set.
func (o *SkyBlockProfileMemberMiningCore) GetPowderGlaciteOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PowderGlacite, true
}

// SetPowderGlacite sets field value
func (o *SkyBlockProfileMemberMiningCore) SetPowderGlacite(v int64) {
	o.PowderGlacite = v
}

// GetPowderGlaciteTotal returns the PowderGlaciteTotal field value
func (o *SkyBlockProfileMemberMiningCore) GetPowderGlaciteTotal() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.PowderGlaciteTotal
}

// GetPowderGlaciteTotalOk returns a tuple with the PowderGlaciteTotal field value
// and a boolean to check if the value has been set.
func (o *SkyBlockProfileMemberMiningCore) GetPowderGlaciteTotalOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PowderGlaciteTotal, true
}

// SetPowderGlaciteTotal sets field value
func (o *SkyBlockProfileMemberMiningCore) SetPowderGlaciteTotal(v int64) {
	o.PowderGlaciteTotal = v
}

// GetPowderMithril returns the PowderMithril field value
func (o *SkyBlockProfileMemberMiningCore) GetPowderMithril() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.PowderMithril
}

// GetPowderMithrilOk returns a tuple with the PowderMithril field value
// and a boolean to check if the value has been set.
func (o *SkyBlockProfileMemberMiningCore) GetPowderMithrilOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PowderMithril, true
}

// SetPowderMithril sets field value
func (o *SkyBlockProfileMemberMiningCore) SetPowderMithril(v int64) {
	o.PowderMithril = v
}

// GetPowderMithrilTotal returns the PowderMithrilTotal field value
func (o *SkyBlockProfileMemberMiningCore) GetPowderMithrilTotal() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.PowderMithrilTotal
}

// GetPowderMithrilTotalOk returns a tuple with the PowderMithrilTotal field value
// and a boolean to check if the value has been set.
func (o *SkyBlockProfileMemberMiningCore) GetPowderMithrilTotalOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PowderMithrilTotal, true
}

// SetPowderMithrilTotal sets field value
func (o *SkyBlockProfileMemberMiningCore) SetPowderMithrilTotal(v int64) {
	o.PowderMithrilTotal = v
}

// GetPowderSpentGemstone returns the PowderSpentGemstone field value
func (o *SkyBlockProfileMemberMiningCore) GetPowderSpentGemstone() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.PowderSpentGemstone
}

// GetPowderSpentGemstoneOk returns a tuple with the PowderSpentGemstone field value
// and a boolean to check if the value has been set.
func (o *SkyBlockProfileMemberMiningCore) GetPowderSpentGemstoneOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PowderSpentGemstone, true
}

// SetPowderSpentGemstone sets field value
func (o *SkyBlockProfileMemberMiningCore) SetPowderSpentGemstone(v int64) {
	o.PowderSpentGemstone = v
}

// GetPowderSpentGlacite returns the PowderSpentGlacite field value
func (o *SkyBlockProfileMemberMiningCore) GetPowderSpentGlacite() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.PowderSpentGlacite
}

// GetPowderSpentGlaciteOk returns a tuple with the PowderSpentGlacite field value
// and a boolean to check if the value has been set.
func (o *SkyBlockProfileMemberMiningCore) GetPowderSpentGlaciteOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PowderSpentGlacite, true
}

// SetPowderSpentGlacite sets field value
func (o *SkyBlockProfileMemberMiningCore) SetPowderSpentGlacite(v int64) {
	o.PowderSpentGlacite = v
}

// GetPowderSpentMithril returns the PowderSpentMithril field value
func (o *SkyBlockProfileMemberMiningCore) GetPowderSpentMithril() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.PowderSpentMithril
}

// GetPowderSpentMithrilOk returns a tuple with the PowderSpentMithril field value
// and a boolean to check if the value has been set.
func (o *SkyBlockProfileMemberMiningCore) GetPowderSpentMithrilOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PowderSpentMithril, true
}

// SetPowderSpentMithril sets field value
func (o *SkyBlockProfileMemberMiningCore) SetPowderSpentMithril(v int64) {
	o.PowderSpentMithril = v
}

// GetReceivedFreeTier returns the ReceivedFreeTier field value
func (o *SkyBlockProfileMemberMiningCore) GetReceivedFreeTier() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ReceivedFreeTier
}

// GetReceivedFreeTierOk returns a tuple with the ReceivedFreeTier field value
// and a boolean to check if the value has been set.
func (o *SkyBlockProfileMemberMiningCore) GetReceivedFreeTierOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReceivedFreeTier, true
}

// SetReceivedFreeTier sets field value
func (o *SkyBlockProfileMemberMiningCore) SetReceivedFreeTier(v bool) {
	o.ReceivedFreeTier = v
}

// GetRetroactiveTier2Token returns the RetroactiveTier2Token field value
func (o *SkyBlockProfileMemberMiningCore) GetRetroactiveTier2Token() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.RetroactiveTier2Token
}

// GetRetroactiveTier2TokenOk returns a tuple with the RetroactiveTier2Token field value
// and a boolean to check if the value has been set.
func (o *SkyBlockProfileMemberMiningCore) GetRetroactiveTier2TokenOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RetroactiveTier2Token, true
}

// SetRetroactiveTier2Token sets field value
func (o *SkyBlockProfileMemberMiningCore) SetRetroactiveTier2Token(v bool) {
	o.RetroactiveTier2Token = v
}

// GetTokensSpent returns the TokensSpent field value
func (o *SkyBlockProfileMemberMiningCore) GetTokensSpent() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.TokensSpent
}

// GetTokensSpentOk returns a tuple with the TokensSpent field value
// and a boolean to check if the value has been set.
func (o *SkyBlockProfileMemberMiningCore) GetTokensSpentOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TokensSpent, true
}

// SetTokensSpent sets field value
func (o *SkyBlockProfileMemberMiningCore) SetTokensSpent(v int64) {
	o.TokensSpent = v
}

func (o SkyBlockProfileMemberMiningCore) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SkyBlockProfileMemberMiningCore) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["biomes"] = o.Biomes
	toSerialize["crystals"] = o.Crystals
	toSerialize["daily_ores_mined"] = o.DailyOresMined
	toSerialize["daily_ores_mined_day"] = o.DailyOresMinedDay
	toSerialize["daily_ores_mined_day_gemstone"] = o.DailyOresMinedDayGemstone
	toSerialize["daily_ores_mined_day_glacite"] = o.DailyOresMinedDayGlacite
	toSerialize["daily_ores_mined_day_mithril_ore"] = o.DailyOresMinedDayMithrilOre
	toSerialize["daily_ores_mined_gemstone"] = o.DailyOresMinedGemstone
	toSerialize["daily_ores_mined_glacite"] = o.DailyOresMinedGlacite
	toSerialize["daily_ores_mined_mithril_ore"] = o.DailyOresMinedMithrilOre
	toSerialize["experience"] = o.Experience
	toSerialize["greater_mines_last_access"] = o.GreaterMinesLastAccess
	toSerialize["last_reset"] = o.LastReset
	toSerialize["nodes"] = o.Nodes
	toSerialize["powder_gemstone"] = o.PowderGemstone
	toSerialize["powder_gemstone_total"] = o.PowderGemstoneTotal
	toSerialize["powder_glacite"] = o.PowderGlacite
	toSerialize["powder_glacite_total"] = o.PowderGlaciteTotal
	toSerialize["powder_mithril"] = o.PowderMithril
	toSerialize["powder_mithril_total"] = o.PowderMithrilTotal
	toSerialize["powder_spent_gemstone"] = o.PowderSpentGemstone
	toSerialize["powder_spent_glacite"] = o.PowderSpentGlacite
	toSerialize["powder_spent_mithril"] = o.PowderSpentMithril
	toSerialize["received_free_tier"] = o.ReceivedFreeTier
	toSerialize["retroactive_tier2_token"] = o.RetroactiveTier2Token
	toSerialize["tokens_spent"] = o.TokensSpent
	return toSerialize, nil
}

func (o *SkyBlockProfileMemberMiningCore) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"biomes",
		"crystals",
		"daily_ores_mined",
		"daily_ores_mined_day",
		"daily_ores_mined_day_gemstone",
		"daily_ores_mined_day_glacite",
		"daily_ores_mined_day_mithril_ore",
		"daily_ores_mined_gemstone",
		"daily_ores_mined_glacite",
		"daily_ores_mined_mithril_ore",
		"experience",
		"greater_mines_last_access",
		"last_reset",
		"nodes",
		"powder_gemstone",
		"powder_gemstone_total",
		"powder_glacite",
		"powder_glacite_total",
		"powder_mithril",
		"powder_mithril_total",
		"powder_spent_gemstone",
		"powder_spent_glacite",
		"powder_spent_mithril",
		"received_free_tier",
		"retroactive_tier2_token",
		"tokens_spent",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSkyBlockProfileMemberMiningCore := _SkyBlockProfileMemberMiningCore{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSkyBlockProfileMemberMiningCore)

	if err != nil {
		return err
	}

	*o = SkyBlockProfileMemberMiningCore(varSkyBlockProfileMemberMiningCore)

	return err
}

type NullableSkyBlockProfileMemberMiningCore struct {
	value *SkyBlockProfileMemberMiningCore
	isSet bool
}

func (v NullableSkyBlockProfileMemberMiningCore) Get() *SkyBlockProfileMemberMiningCore {
	return v.value
}

func (v *NullableSkyBlockProfileMemberMiningCore) Set(val *SkyBlockProfileMemberMiningCore) {
	v.value = val
	v.isSet = true
}

func (v NullableSkyBlockProfileMemberMiningCore) IsSet() bool {
	return v.isSet
}

func (v *NullableSkyBlockProfileMemberMiningCore) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSkyBlockProfileMemberMiningCore(val *SkyBlockProfileMemberMiningCore) *NullableSkyBlockProfileMemberMiningCore {
	return &NullableSkyBlockProfileMemberMiningCore{value: val, isSet: true}
}

func (v NullableSkyBlockProfileMemberMiningCore) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSkyBlockProfileMemberMiningCore) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
