/*
Hypixel Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SkyBlockProfileMemberEventsEasterRabbitsCollectedEggs type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SkyBlockProfileMemberEventsEasterRabbitsCollectedEggs{}

// SkyBlockProfileMemberEventsEasterRabbitsCollectedEggs struct for SkyBlockProfileMemberEventsEasterRabbitsCollectedEggs
type SkyBlockProfileMemberEventsEasterRabbitsCollectedEggs struct {
	Breakfast *int64 `json:"breakfast,omitempty"`
	Brunch    *int64 `json:"brunch,omitempty"`
	Dejeuner  *int64 `json:"dejeuner,omitempty"`
	Dinner    *int64 `json:"dinner,omitempty"`
	Lunch     *int64 `json:"lunch,omitempty"`
	Supper    *int64 `json:"supper,omitempty"`
}

// NewSkyBlockProfileMemberEventsEasterRabbitsCollectedEggs instantiates a new SkyBlockProfileMemberEventsEasterRabbitsCollectedEggs object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSkyBlockProfileMemberEventsEasterRabbitsCollectedEggs() *SkyBlockProfileMemberEventsEasterRabbitsCollectedEggs {
	this := SkyBlockProfileMemberEventsEasterRabbitsCollectedEggs{}
	return &this
}

// NewSkyBlockProfileMemberEventsEasterRabbitsCollectedEggsWithDefaults instantiates a new SkyBlockProfileMemberEventsEasterRabbitsCollectedEggs object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSkyBlockProfileMemberEventsEasterRabbitsCollectedEggsWithDefaults() *SkyBlockProfileMemberEventsEasterRabbitsCollectedEggs {
	this := SkyBlockProfileMemberEventsEasterRabbitsCollectedEggs{}
	return &this
}

// GetBreakfast returns the Breakfast field value if set, zero value otherwise.
func (o *SkyBlockProfileMemberEventsEasterRabbitsCollectedEggs) GetBreakfast() int64 {
	if o == nil || IsNil(o.Breakfast) {
		var ret int64
		return ret
	}
	return *o.Breakfast
}

// GetBreakfastOk returns a tuple with the Breakfast field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SkyBlockProfileMemberEventsEasterRabbitsCollectedEggs) GetBreakfastOk() (*int64, bool) {
	if o == nil || IsNil(o.Breakfast) {
		return nil, false
	}
	return o.Breakfast, true
}

// HasBreakfast returns a boolean if a field has been set.
func (o *SkyBlockProfileMemberEventsEasterRabbitsCollectedEggs) HasBreakfast() bool {
	if o != nil && !IsNil(o.Breakfast) {
		return true
	}

	return false
}

// SetBreakfast gets a reference to the given int64 and assigns it to the Breakfast field.
func (o *SkyBlockProfileMemberEventsEasterRabbitsCollectedEggs) SetBreakfast(v int64) {
	o.Breakfast = &v
}

// GetBrunch returns the Brunch field value if set, zero value otherwise.
func (o *SkyBlockProfileMemberEventsEasterRabbitsCollectedEggs) GetBrunch() int64 {
	if o == nil || IsNil(o.Brunch) {
		var ret int64
		return ret
	}
	return *o.Brunch
}

// GetBrunchOk returns a tuple with the Brunch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SkyBlockProfileMemberEventsEasterRabbitsCollectedEggs) GetBrunchOk() (*int64, bool) {
	if o == nil || IsNil(o.Brunch) {
		return nil, false
	}
	return o.Brunch, true
}

// HasBrunch returns a boolean if a field has been set.
func (o *SkyBlockProfileMemberEventsEasterRabbitsCollectedEggs) HasBrunch() bool {
	if o != nil && !IsNil(o.Brunch) {
		return true
	}

	return false
}

// SetBrunch gets a reference to the given int64 and assigns it to the Brunch field.
func (o *SkyBlockProfileMemberEventsEasterRabbitsCollectedEggs) SetBrunch(v int64) {
	o.Brunch = &v
}

// GetDejeuner returns the Dejeuner field value if set, zero value otherwise.
func (o *SkyBlockProfileMemberEventsEasterRabbitsCollectedEggs) GetDejeuner() int64 {
	if o == nil || IsNil(o.Dejeuner) {
		var ret int64
		return ret
	}
	return *o.Dejeuner
}

// GetDejeunerOk returns a tuple with the Dejeuner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SkyBlockProfileMemberEventsEasterRabbitsCollectedEggs) GetDejeunerOk() (*int64, bool) {
	if o == nil || IsNil(o.Dejeuner) {
		return nil, false
	}
	return o.Dejeuner, true
}

// HasDejeuner returns a boolean if a field has been set.
func (o *SkyBlockProfileMemberEventsEasterRabbitsCollectedEggs) HasDejeuner() bool {
	if o != nil && !IsNil(o.Dejeuner) {
		return true
	}

	return false
}

// SetDejeuner gets a reference to the given int64 and assigns it to the Dejeuner field.
func (o *SkyBlockProfileMemberEventsEasterRabbitsCollectedEggs) SetDejeuner(v int64) {
	o.Dejeuner = &v
}

// GetDinner returns the Dinner field value if set, zero value otherwise.
func (o *SkyBlockProfileMemberEventsEasterRabbitsCollectedEggs) GetDinner() int64 {
	if o == nil || IsNil(o.Dinner) {
		var ret int64
		return ret
	}
	return *o.Dinner
}

// GetDinnerOk returns a tuple with the Dinner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SkyBlockProfileMemberEventsEasterRabbitsCollectedEggs) GetDinnerOk() (*int64, bool) {
	if o == nil || IsNil(o.Dinner) {
		return nil, false
	}
	return o.Dinner, true
}

// HasDinner returns a boolean if a field has been set.
func (o *SkyBlockProfileMemberEventsEasterRabbitsCollectedEggs) HasDinner() bool {
	if o != nil && !IsNil(o.Dinner) {
		return true
	}

	return false
}

// SetDinner gets a reference to the given int64 and assigns it to the Dinner field.
func (o *SkyBlockProfileMemberEventsEasterRabbitsCollectedEggs) SetDinner(v int64) {
	o.Dinner = &v
}

// GetLunch returns the Lunch field value if set, zero value otherwise.
func (o *SkyBlockProfileMemberEventsEasterRabbitsCollectedEggs) GetLunch() int64 {
	if o == nil || IsNil(o.Lunch) {
		var ret int64
		return ret
	}
	return *o.Lunch
}

// GetLunchOk returns a tuple with the Lunch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SkyBlockProfileMemberEventsEasterRabbitsCollectedEggs) GetLunchOk() (*int64, bool) {
	if o == nil || IsNil(o.Lunch) {
		return nil, false
	}
	return o.Lunch, true
}

// HasLunch returns a boolean if a field has been set.
func (o *SkyBlockProfileMemberEventsEasterRabbitsCollectedEggs) HasLunch() bool {
	if o != nil && !IsNil(o.Lunch) {
		return true
	}

	return false
}

// SetLunch gets a reference to the given int64 and assigns it to the Lunch field.
func (o *SkyBlockProfileMemberEventsEasterRabbitsCollectedEggs) SetLunch(v int64) {
	o.Lunch = &v
}

// GetSupper returns the Supper field value if set, zero value otherwise.
func (o *SkyBlockProfileMemberEventsEasterRabbitsCollectedEggs) GetSupper() int64 {
	if o == nil || IsNil(o.Supper) {
		var ret int64
		return ret
	}
	return *o.Supper
}

// GetSupperOk returns a tuple with the Supper field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SkyBlockProfileMemberEventsEasterRabbitsCollectedEggs) GetSupperOk() (*int64, bool) {
	if o == nil || IsNil(o.Supper) {
		return nil, false
	}
	return o.Supper, true
}

// HasSupper returns a boolean if a field has been set.
func (o *SkyBlockProfileMemberEventsEasterRabbitsCollectedEggs) HasSupper() bool {
	if o != nil && !IsNil(o.Supper) {
		return true
	}

	return false
}

// SetSupper gets a reference to the given int64 and assigns it to the Supper field.
func (o *SkyBlockProfileMemberEventsEasterRabbitsCollectedEggs) SetSupper(v int64) {
	o.Supper = &v
}

func (o SkyBlockProfileMemberEventsEasterRabbitsCollectedEggs) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SkyBlockProfileMemberEventsEasterRabbitsCollectedEggs) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Breakfast) {
		toSerialize["breakfast"] = o.Breakfast
	}
	if !IsNil(o.Brunch) {
		toSerialize["brunch"] = o.Brunch
	}
	if !IsNil(o.Dejeuner) {
		toSerialize["dejeuner"] = o.Dejeuner
	}
	if !IsNil(o.Dinner) {
		toSerialize["dinner"] = o.Dinner
	}
	if !IsNil(o.Lunch) {
		toSerialize["lunch"] = o.Lunch
	}
	if !IsNil(o.Supper) {
		toSerialize["supper"] = o.Supper
	}
	return toSerialize, nil
}

type NullableSkyBlockProfileMemberEventsEasterRabbitsCollectedEggs struct {
	value *SkyBlockProfileMemberEventsEasterRabbitsCollectedEggs
	isSet bool
}

func (v NullableSkyBlockProfileMemberEventsEasterRabbitsCollectedEggs) Get() *SkyBlockProfileMemberEventsEasterRabbitsCollectedEggs {
	return v.value
}

func (v *NullableSkyBlockProfileMemberEventsEasterRabbitsCollectedEggs) Set(val *SkyBlockProfileMemberEventsEasterRabbitsCollectedEggs) {
	v.value = val
	v.isSet = true
}

func (v NullableSkyBlockProfileMemberEventsEasterRabbitsCollectedEggs) IsSet() bool {
	return v.isSet
}

func (v *NullableSkyBlockProfileMemberEventsEasterRabbitsCollectedEggs) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSkyBlockProfileMemberEventsEasterRabbitsCollectedEggs(val *SkyBlockProfileMemberEventsEasterRabbitsCollectedEggs) *NullableSkyBlockProfileMemberEventsEasterRabbitsCollectedEggs {
	return &NullableSkyBlockProfileMemberEventsEasterRabbitsCollectedEggs{value: val, isSet: true}
}

func (v NullableSkyBlockProfileMemberEventsEasterRabbitsCollectedEggs) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSkyBlockProfileMemberEventsEasterRabbitsCollectedEggs) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
