/*
Hypixel Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SkyBlockProfileMemberRiftWizardTower type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SkyBlockProfileMemberRiftWizardTower{}

// SkyBlockProfileMemberRiftWizardTower struct for SkyBlockProfileMemberRiftWizardTower
type SkyBlockProfileMemberRiftWizardTower struct {
	CrumbsLaidOut   *int64 `json:"crumbs_laid_out,omitempty"`
	WizardQuestStep *int64 `json:"wizard_quest_step,omitempty"`
}

// NewSkyBlockProfileMemberRiftWizardTower instantiates a new SkyBlockProfileMemberRiftWizardTower object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSkyBlockProfileMemberRiftWizardTower() *SkyBlockProfileMemberRiftWizardTower {
	this := SkyBlockProfileMemberRiftWizardTower{}
	return &this
}

// NewSkyBlockProfileMemberRiftWizardTowerWithDefaults instantiates a new SkyBlockProfileMemberRiftWizardTower object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSkyBlockProfileMemberRiftWizardTowerWithDefaults() *SkyBlockProfileMemberRiftWizardTower {
	this := SkyBlockProfileMemberRiftWizardTower{}
	return &this
}

// GetCrumbsLaidOut returns the CrumbsLaidOut field value if set, zero value otherwise.
func (o *SkyBlockProfileMemberRiftWizardTower) GetCrumbsLaidOut() int64 {
	if o == nil || IsNil(o.CrumbsLaidOut) {
		var ret int64
		return ret
	}
	return *o.CrumbsLaidOut
}

// GetCrumbsLaidOutOk returns a tuple with the CrumbsLaidOut field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SkyBlockProfileMemberRiftWizardTower) GetCrumbsLaidOutOk() (*int64, bool) {
	if o == nil || IsNil(o.CrumbsLaidOut) {
		return nil, false
	}
	return o.CrumbsLaidOut, true
}

// HasCrumbsLaidOut returns a boolean if a field has been set.
func (o *SkyBlockProfileMemberRiftWizardTower) HasCrumbsLaidOut() bool {
	if o != nil && !IsNil(o.CrumbsLaidOut) {
		return true
	}

	return false
}

// SetCrumbsLaidOut gets a reference to the given int64 and assigns it to the CrumbsLaidOut field.
func (o *SkyBlockProfileMemberRiftWizardTower) SetCrumbsLaidOut(v int64) {
	o.CrumbsLaidOut = &v
}

// GetWizardQuestStep returns the WizardQuestStep field value if set, zero value otherwise.
func (o *SkyBlockProfileMemberRiftWizardTower) GetWizardQuestStep() int64 {
	if o == nil || IsNil(o.WizardQuestStep) {
		var ret int64
		return ret
	}
	return *o.WizardQuestStep
}

// GetWizardQuestStepOk returns a tuple with the WizardQuestStep field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SkyBlockProfileMemberRiftWizardTower) GetWizardQuestStepOk() (*int64, bool) {
	if o == nil || IsNil(o.WizardQuestStep) {
		return nil, false
	}
	return o.WizardQuestStep, true
}

// HasWizardQuestStep returns a boolean if a field has been set.
func (o *SkyBlockProfileMemberRiftWizardTower) HasWizardQuestStep() bool {
	if o != nil && !IsNil(o.WizardQuestStep) {
		return true
	}

	return false
}

// SetWizardQuestStep gets a reference to the given int64 and assigns it to the WizardQuestStep field.
func (o *SkyBlockProfileMemberRiftWizardTower) SetWizardQuestStep(v int64) {
	o.WizardQuestStep = &v
}

func (o SkyBlockProfileMemberRiftWizardTower) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SkyBlockProfileMemberRiftWizardTower) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CrumbsLaidOut) {
		toSerialize["crumbs_laid_out"] = o.CrumbsLaidOut
	}
	if !IsNil(o.WizardQuestStep) {
		toSerialize["wizard_quest_step"] = o.WizardQuestStep
	}
	return toSerialize, nil
}

type NullableSkyBlockProfileMemberRiftWizardTower struct {
	value *SkyBlockProfileMemberRiftWizardTower
	isSet bool
}

func (v NullableSkyBlockProfileMemberRiftWizardTower) Get() *SkyBlockProfileMemberRiftWizardTower {
	return v.value
}

func (v *NullableSkyBlockProfileMemberRiftWizardTower) Set(val *SkyBlockProfileMemberRiftWizardTower) {
	v.value = val
	v.isSet = true
}

func (v NullableSkyBlockProfileMemberRiftWizardTower) IsSet() bool {
	return v.isSet
}

func (v *NullableSkyBlockProfileMemberRiftWizardTower) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSkyBlockProfileMemberRiftWizardTower(val *SkyBlockProfileMemberRiftWizardTower) *NullableSkyBlockProfileMemberRiftWizardTower {
	return &NullableSkyBlockProfileMemberRiftWizardTower{value: val, isSet: true}
}

func (v NullableSkyBlockProfileMemberRiftWizardTower) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSkyBlockProfileMemberRiftWizardTower) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
