/*
Hypixel Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// SkyBlockProfileMemberRiftWestVillageCrazyKloonHackedTerminalsInner the model 'SkyBlockProfileMemberRiftWestVillageCrazyKloonHackedTerminalsInner'
type SkyBlockProfileMemberRiftWestVillageCrazyKloonHackedTerminalsInner string

// List of SkyBlockProfileMemberRiftWestVillageCrazyKloon_hacked_terminals_inner
const (
	SKYBLOCKPROFILEMEMBERRIFTWESTVILLAGECRAZYKLOONHACKEDTERMINALSINNER_EIGHT SkyBlockProfileMemberRiftWestVillageCrazyKloonHackedTerminalsInner = "eight"
	SKYBLOCKPROFILEMEMBERRIFTWESTVILLAGECRAZYKLOONHACKEDTERMINALSINNER_FIVE  SkyBlockProfileMemberRiftWestVillageCrazyKloonHackedTerminalsInner = "five"
	SKYBLOCKPROFILEMEMBERRIFTWESTVILLAGECRAZYKLOONHACKEDTERMINALSINNER_FOUR  SkyBlockProfileMemberRiftWestVillageCrazyKloonHackedTerminalsInner = "four"
	SKYBLOCKPROFILEMEMBERRIFTWESTVILLAGECRAZYKLOONHACKEDTERMINALSINNER_ONE   SkyBlockProfileMemberRiftWestVillageCrazyKloonHackedTerminalsInner = "one"
	SKYBLOCKPROFILEMEMBERRIFTWESTVILLAGECRAZYKLOONHACKEDTERMINALSINNER_SEVEN SkyBlockProfileMemberRiftWestVillageCrazyKloonHackedTerminalsInner = "seven"
	SKYBLOCKPROFILEMEMBERRIFTWESTVILLAGECRAZYKLOONHACKEDTERMINALSINNER_SIX   SkyBlockProfileMemberRiftWestVillageCrazyKloonHackedTerminalsInner = "six"
	SKYBLOCKPROFILEMEMBERRIFTWESTVILLAGECRAZYKLOONHACKEDTERMINALSINNER_THREE SkyBlockProfileMemberRiftWestVillageCrazyKloonHackedTerminalsInner = "three"
	SKYBLOCKPROFILEMEMBERRIFTWESTVILLAGECRAZYKLOONHACKEDTERMINALSINNER_TWO   SkyBlockProfileMemberRiftWestVillageCrazyKloonHackedTerminalsInner = "two"
)

// All allowed values of SkyBlockProfileMemberRiftWestVillageCrazyKloonHackedTerminalsInner enum
var AllowedSkyBlockProfileMemberRiftWestVillageCrazyKloonHackedTerminalsInnerEnumValues = []SkyBlockProfileMemberRiftWestVillageCrazyKloonHackedTerminalsInner{
	"eight",
	"five",
	"four",
	"one",
	"seven",
	"six",
	"three",
	"two",
}

func (v *SkyBlockProfileMemberRiftWestVillageCrazyKloonHackedTerminalsInner) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SkyBlockProfileMemberRiftWestVillageCrazyKloonHackedTerminalsInner(value)
	for _, existing := range AllowedSkyBlockProfileMemberRiftWestVillageCrazyKloonHackedTerminalsInnerEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid SkyBlockProfileMemberRiftWestVillageCrazyKloonHackedTerminalsInner", value)
}

// NewSkyBlockProfileMemberRiftWestVillageCrazyKloonHackedTerminalsInnerFromValue returns a pointer to a valid SkyBlockProfileMemberRiftWestVillageCrazyKloonHackedTerminalsInner
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSkyBlockProfileMemberRiftWestVillageCrazyKloonHackedTerminalsInnerFromValue(v string) (*SkyBlockProfileMemberRiftWestVillageCrazyKloonHackedTerminalsInner, error) {
	ev := SkyBlockProfileMemberRiftWestVillageCrazyKloonHackedTerminalsInner(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for SkyBlockProfileMemberRiftWestVillageCrazyKloonHackedTerminalsInner: valid values are %v", v, AllowedSkyBlockProfileMemberRiftWestVillageCrazyKloonHackedTerminalsInnerEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v SkyBlockProfileMemberRiftWestVillageCrazyKloonHackedTerminalsInner) IsValid() bool {
	for _, existing := range AllowedSkyBlockProfileMemberRiftWestVillageCrazyKloonHackedTerminalsInnerEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to SkyBlockProfileMemberRiftWestVillageCrazyKloon_hacked_terminals_inner value
func (v SkyBlockProfileMemberRiftWestVillageCrazyKloonHackedTerminalsInner) Ptr() *SkyBlockProfileMemberRiftWestVillageCrazyKloonHackedTerminalsInner {
	return &v
}

type NullableSkyBlockProfileMemberRiftWestVillageCrazyKloonHackedTerminalsInner struct {
	value *SkyBlockProfileMemberRiftWestVillageCrazyKloonHackedTerminalsInner
	isSet bool
}

func (v NullableSkyBlockProfileMemberRiftWestVillageCrazyKloonHackedTerminalsInner) Get() *SkyBlockProfileMemberRiftWestVillageCrazyKloonHackedTerminalsInner {
	return v.value
}

func (v *NullableSkyBlockProfileMemberRiftWestVillageCrazyKloonHackedTerminalsInner) Set(val *SkyBlockProfileMemberRiftWestVillageCrazyKloonHackedTerminalsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableSkyBlockProfileMemberRiftWestVillageCrazyKloonHackedTerminalsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableSkyBlockProfileMemberRiftWestVillageCrazyKloonHackedTerminalsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSkyBlockProfileMemberRiftWestVillageCrazyKloonHackedTerminalsInner(val *SkyBlockProfileMemberRiftWestVillageCrazyKloonHackedTerminalsInner) *NullableSkyBlockProfileMemberRiftWestVillageCrazyKloonHackedTerminalsInner {
	return &NullableSkyBlockProfileMemberRiftWestVillageCrazyKloonHackedTerminalsInner{value: val, isSet: true}
}

func (v NullableSkyBlockProfileMemberRiftWestVillageCrazyKloonHackedTerminalsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSkyBlockProfileMemberRiftWestVillageCrazyKloonHackedTerminalsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
