/*
Hypixel Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// SkyBlockProfileMemberEventsEasterRabbitsCollectedLocationsFishing1Inner the model 'SkyBlockProfileMemberEventsEasterRabbitsCollectedLocationsFishing1Inner'
type SkyBlockProfileMemberEventsEasterRabbitsCollectedLocationsFishing1Inner string

// List of SkyBlockProfileMemberEventsEasterRabbitsCollectedLocations_fishing_1_inner
const (
	SKYBLOCKPROFILEMEMBEREVENTSEASTERRABBITSCOLLECTEDLOCATIONSFISHING1INNER_BAYOU_BRIDGE      SkyBlockProfileMemberEventsEasterRabbitsCollectedLocationsFishing1Inner = "bayou_bridge"
	SKYBLOCKPROFILEMEMBEREVENTSEASTERRABBITSCOLLECTEDLOCATIONSFISHING1INNER_BAYOU_CAVE        SkyBlockProfileMemberEventsEasterRabbitsCollectedLocationsFishing1Inner = "bayou_cave"
	SKYBLOCKPROFILEMEMBEREVENTSEASTERRABBITSCOLLECTEDLOCATIONSFISHING1INNER_BAYOU_DOCK        SkyBlockProfileMemberEventsEasterRabbitsCollectedLocationsFishing1Inner = "bayou_dock"
	SKYBLOCKPROFILEMEMBEREVENTSEASTERRABBITSCOLLECTEDLOCATIONSFISHING1INNER_BAYOU_GEAR        SkyBlockProfileMemberEventsEasterRabbitsCollectedLocationsFishing1Inner = "bayou_gear"
	SKYBLOCKPROFILEMEMBEREVENTSEASTERRABBITSCOLLECTEDLOCATIONSFISHING1INNER_BAYOU_HATTIE      SkyBlockProfileMemberEventsEasterRabbitsCollectedLocationsFishing1Inner = "bayou_hattie"
	SKYBLOCKPROFILEMEMBEREVENTSEASTERRABBITSCOLLECTEDLOCATIONSFISHING1INNER_BAYOU_JOEL        SkyBlockProfileMemberEventsEasterRabbitsCollectedLocationsFishing1Inner = "bayou_joel"
	SKYBLOCKPROFILEMEMBEREVENTSEASTERRABBITSCOLLECTEDLOCATIONSFISHING1INNER_BAYOU_LILYPAD     SkyBlockProfileMemberEventsEasterRabbitsCollectedLocationsFishing1Inner = "bayou_lilypad"
	SKYBLOCKPROFILEMEMBEREVENTSEASTERRABBITSCOLLECTEDLOCATIONSFISHING1INNER_BAYOU_PATH        SkyBlockProfileMemberEventsEasterRabbitsCollectedLocationsFishing1Inner = "bayou_path"
	SKYBLOCKPROFILEMEMBEREVENTSEASTERRABBITSCOLLECTEDLOCATIONSFISHING1INNER_BAYOU_PIPE        SkyBlockProfileMemberEventsEasterRabbitsCollectedLocationsFishing1Inner = "bayou_pipe"
	SKYBLOCKPROFILEMEMBEREVENTSEASTERRABBITSCOLLECTEDLOCATIONSFISHING1INNER_BAYOU_RODDY       SkyBlockProfileMemberEventsEasterRabbitsCollectedLocationsFishing1Inner = "bayou_roddy"
	SKYBLOCKPROFILEMEMBEREVENTSEASTERRABBITSCOLLECTEDLOCATIONSFISHING1INNER_BAYOU_SHIP        SkyBlockProfileMemberEventsEasterRabbitsCollectedLocationsFishing1Inner = "bayou_ship"
	SKYBLOCKPROFILEMEMBEREVENTSEASTERRABBITSCOLLECTEDLOCATIONSFISHING1INNER_BAYOU_SMOKESTACKS SkyBlockProfileMemberEventsEasterRabbitsCollectedLocationsFishing1Inner = "bayou_smokestacks"
	SKYBLOCKPROFILEMEMBEREVENTSEASTERRABBITSCOLLECTEDLOCATIONSFISHING1INNER_BAYOU_VINES       SkyBlockProfileMemberEventsEasterRabbitsCollectedLocationsFishing1Inner = "bayou_vines"
	SKYBLOCKPROFILEMEMBEREVENTSEASTERRABBITSCOLLECTEDLOCATIONSFISHING1INNER_BAYOU_WATERFALL   SkyBlockProfileMemberEventsEasterRabbitsCollectedLocationsFishing1Inner = "bayou_waterfall"
	SKYBLOCKPROFILEMEMBEREVENTSEASTERRABBITSCOLLECTEDLOCATIONSFISHING1INNER_BAYOU_WHEEL       SkyBlockProfileMemberEventsEasterRabbitsCollectedLocationsFishing1Inner = "bayou_wheel"
)

// All allowed values of SkyBlockProfileMemberEventsEasterRabbitsCollectedLocationsFishing1Inner enum
var AllowedSkyBlockProfileMemberEventsEasterRabbitsCollectedLocationsFishing1InnerEnumValues = []SkyBlockProfileMemberEventsEasterRabbitsCollectedLocationsFishing1Inner{
	"bayou_bridge",
	"bayou_cave",
	"bayou_dock",
	"bayou_gear",
	"bayou_hattie",
	"bayou_joel",
	"bayou_lilypad",
	"bayou_path",
	"bayou_pipe",
	"bayou_roddy",
	"bayou_ship",
	"bayou_smokestacks",
	"bayou_vines",
	"bayou_waterfall",
	"bayou_wheel",
}

func (v *SkyBlockProfileMemberEventsEasterRabbitsCollectedLocationsFishing1Inner) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SkyBlockProfileMemberEventsEasterRabbitsCollectedLocationsFishing1Inner(value)
	for _, existing := range AllowedSkyBlockProfileMemberEventsEasterRabbitsCollectedLocationsFishing1InnerEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid SkyBlockProfileMemberEventsEasterRabbitsCollectedLocationsFishing1Inner", value)
}

// NewSkyBlockProfileMemberEventsEasterRabbitsCollectedLocationsFishing1InnerFromValue returns a pointer to a valid SkyBlockProfileMemberEventsEasterRabbitsCollectedLocationsFishing1Inner
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSkyBlockProfileMemberEventsEasterRabbitsCollectedLocationsFishing1InnerFromValue(v string) (*SkyBlockProfileMemberEventsEasterRabbitsCollectedLocationsFishing1Inner, error) {
	ev := SkyBlockProfileMemberEventsEasterRabbitsCollectedLocationsFishing1Inner(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for SkyBlockProfileMemberEventsEasterRabbitsCollectedLocationsFishing1Inner: valid values are %v", v, AllowedSkyBlockProfileMemberEventsEasterRabbitsCollectedLocationsFishing1InnerEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v SkyBlockProfileMemberEventsEasterRabbitsCollectedLocationsFishing1Inner) IsValid() bool {
	for _, existing := range AllowedSkyBlockProfileMemberEventsEasterRabbitsCollectedLocationsFishing1InnerEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to SkyBlockProfileMemberEventsEasterRabbitsCollectedLocations_fishing_1_inner value
func (v SkyBlockProfileMemberEventsEasterRabbitsCollectedLocationsFishing1Inner) Ptr() *SkyBlockProfileMemberEventsEasterRabbitsCollectedLocationsFishing1Inner {
	return &v
}

type NullableSkyBlockProfileMemberEventsEasterRabbitsCollectedLocationsFishing1Inner struct {
	value *SkyBlockProfileMemberEventsEasterRabbitsCollectedLocationsFishing1Inner
	isSet bool
}

func (v NullableSkyBlockProfileMemberEventsEasterRabbitsCollectedLocationsFishing1Inner) Get() *SkyBlockProfileMemberEventsEasterRabbitsCollectedLocationsFishing1Inner {
	return v.value
}

func (v *NullableSkyBlockProfileMemberEventsEasterRabbitsCollectedLocationsFishing1Inner) Set(val *SkyBlockProfileMemberEventsEasterRabbitsCollectedLocationsFishing1Inner) {
	v.value = val
	v.isSet = true
}

func (v NullableSkyBlockProfileMemberEventsEasterRabbitsCollectedLocationsFishing1Inner) IsSet() bool {
	return v.isSet
}

func (v *NullableSkyBlockProfileMemberEventsEasterRabbitsCollectedLocationsFishing1Inner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSkyBlockProfileMemberEventsEasterRabbitsCollectedLocationsFishing1Inner(val *SkyBlockProfileMemberEventsEasterRabbitsCollectedLocationsFishing1Inner) *NullableSkyBlockProfileMemberEventsEasterRabbitsCollectedLocationsFishing1Inner {
	return &NullableSkyBlockProfileMemberEventsEasterRabbitsCollectedLocationsFishing1Inner{value: val, isSet: true}
}

func (v NullableSkyBlockProfileMemberEventsEasterRabbitsCollectedLocationsFishing1Inner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSkyBlockProfileMemberEventsEasterRabbitsCollectedLocationsFishing1Inner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
