/*
Hypixel Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SkyBlockProfileMemberFairySoul type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SkyBlockProfileMemberFairySoul{}

// SkyBlockProfileMemberFairySoul struct for SkyBlockProfileMemberFairySoul
type SkyBlockProfileMemberFairySoul struct {
	FairyExchanges *int64 `json:"fairy_exchanges,omitempty"`
	TotalCollected *int64 `json:"total_collected,omitempty"`
	UnspentSouls   *int64 `json:"unspent_souls,omitempty"`
}

// NewSkyBlockProfileMemberFairySoul instantiates a new SkyBlockProfileMemberFairySoul object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSkyBlockProfileMemberFairySoul() *SkyBlockProfileMemberFairySoul {
	this := SkyBlockProfileMemberFairySoul{}
	return &this
}

// NewSkyBlockProfileMemberFairySoulWithDefaults instantiates a new SkyBlockProfileMemberFairySoul object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSkyBlockProfileMemberFairySoulWithDefaults() *SkyBlockProfileMemberFairySoul {
	this := SkyBlockProfileMemberFairySoul{}
	return &this
}

// GetFairyExchanges returns the FairyExchanges field value if set, zero value otherwise.
func (o *SkyBlockProfileMemberFairySoul) GetFairyExchanges() int64 {
	if o == nil || IsNil(o.FairyExchanges) {
		var ret int64
		return ret
	}
	return *o.FairyExchanges
}

// GetFairyExchangesOk returns a tuple with the FairyExchanges field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SkyBlockProfileMemberFairySoul) GetFairyExchangesOk() (*int64, bool) {
	if o == nil || IsNil(o.FairyExchanges) {
		return nil, false
	}
	return o.FairyExchanges, true
}

// HasFairyExchanges returns a boolean if a field has been set.
func (o *SkyBlockProfileMemberFairySoul) HasFairyExchanges() bool {
	if o != nil && !IsNil(o.FairyExchanges) {
		return true
	}

	return false
}

// SetFairyExchanges gets a reference to the given int64 and assigns it to the FairyExchanges field.
func (o *SkyBlockProfileMemberFairySoul) SetFairyExchanges(v int64) {
	o.FairyExchanges = &v
}

// GetTotalCollected returns the TotalCollected field value if set, zero value otherwise.
func (o *SkyBlockProfileMemberFairySoul) GetTotalCollected() int64 {
	if o == nil || IsNil(o.TotalCollected) {
		var ret int64
		return ret
	}
	return *o.TotalCollected
}

// GetTotalCollectedOk returns a tuple with the TotalCollected field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SkyBlockProfileMemberFairySoul) GetTotalCollectedOk() (*int64, bool) {
	if o == nil || IsNil(o.TotalCollected) {
		return nil, false
	}
	return o.TotalCollected, true
}

// HasTotalCollected returns a boolean if a field has been set.
func (o *SkyBlockProfileMemberFairySoul) HasTotalCollected() bool {
	if o != nil && !IsNil(o.TotalCollected) {
		return true
	}

	return false
}

// SetTotalCollected gets a reference to the given int64 and assigns it to the TotalCollected field.
func (o *SkyBlockProfileMemberFairySoul) SetTotalCollected(v int64) {
	o.TotalCollected = &v
}

// GetUnspentSouls returns the UnspentSouls field value if set, zero value otherwise.
func (o *SkyBlockProfileMemberFairySoul) GetUnspentSouls() int64 {
	if o == nil || IsNil(o.UnspentSouls) {
		var ret int64
		return ret
	}
	return *o.UnspentSouls
}

// GetUnspentSoulsOk returns a tuple with the UnspentSouls field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SkyBlockProfileMemberFairySoul) GetUnspentSoulsOk() (*int64, bool) {
	if o == nil || IsNil(o.UnspentSouls) {
		return nil, false
	}
	return o.UnspentSouls, true
}

// HasUnspentSouls returns a boolean if a field has been set.
func (o *SkyBlockProfileMemberFairySoul) HasUnspentSouls() bool {
	if o != nil && !IsNil(o.UnspentSouls) {
		return true
	}

	return false
}

// SetUnspentSouls gets a reference to the given int64 and assigns it to the UnspentSouls field.
func (o *SkyBlockProfileMemberFairySoul) SetUnspentSouls(v int64) {
	o.UnspentSouls = &v
}

func (o SkyBlockProfileMemberFairySoul) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SkyBlockProfileMemberFairySoul) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FairyExchanges) {
		toSerialize["fairy_exchanges"] = o.FairyExchanges
	}
	if !IsNil(o.TotalCollected) {
		toSerialize["total_collected"] = o.TotalCollected
	}
	if !IsNil(o.UnspentSouls) {
		toSerialize["unspent_souls"] = o.UnspentSouls
	}
	return toSerialize, nil
}

type NullableSkyBlockProfileMemberFairySoul struct {
	value *SkyBlockProfileMemberFairySoul
	isSet bool
}

func (v NullableSkyBlockProfileMemberFairySoul) Get() *SkyBlockProfileMemberFairySoul {
	return v.value
}

func (v *NullableSkyBlockProfileMemberFairySoul) Set(val *SkyBlockProfileMemberFairySoul) {
	v.value = val
	v.isSet = true
}

func (v NullableSkyBlockProfileMemberFairySoul) IsSet() bool {
	return v.isSet
}

func (v *NullableSkyBlockProfileMemberFairySoul) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSkyBlockProfileMemberFairySoul(val *SkyBlockProfileMemberFairySoul) *NullableSkyBlockProfileMemberFairySoul {
	return &NullableSkyBlockProfileMemberFairySoul{value: val, isSet: true}
}

func (v NullableSkyBlockProfileMemberFairySoul) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSkyBlockProfileMemberFairySoul) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
