/*
Hypixel Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SkyBlockProfileMemberNetherIslandPlayerQuestsSuusQuest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SkyBlockProfileMemberNetherIslandPlayerQuestsSuusQuest{}

// SkyBlockProfileMemberNetherIslandPlayerQuestsSuusQuest struct for SkyBlockProfileMemberNetherIslandPlayerQuestsSuusQuest
type SkyBlockProfileMemberNetherIslandPlayerQuestsSuusQuest struct {
	LastCompletion *int64 `json:"last_completion,omitempty"`
	LastToyDrop    *int64 `json:"last_toy_drop,omitempty"`
	TalkedToNpc    *bool  `json:"talked_to_npc,omitempty"`
}

// NewSkyBlockProfileMemberNetherIslandPlayerQuestsSuusQuest instantiates a new SkyBlockProfileMemberNetherIslandPlayerQuestsSuusQuest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSkyBlockProfileMemberNetherIslandPlayerQuestsSuusQuest() *SkyBlockProfileMemberNetherIslandPlayerQuestsSuusQuest {
	this := SkyBlockProfileMemberNetherIslandPlayerQuestsSuusQuest{}
	return &this
}

// NewSkyBlockProfileMemberNetherIslandPlayerQuestsSuusQuestWithDefaults instantiates a new SkyBlockProfileMemberNetherIslandPlayerQuestsSuusQuest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSkyBlockProfileMemberNetherIslandPlayerQuestsSuusQuestWithDefaults() *SkyBlockProfileMemberNetherIslandPlayerQuestsSuusQuest {
	this := SkyBlockProfileMemberNetherIslandPlayerQuestsSuusQuest{}
	return &this
}

// GetLastCompletion returns the LastCompletion field value if set, zero value otherwise.
func (o *SkyBlockProfileMemberNetherIslandPlayerQuestsSuusQuest) GetLastCompletion() int64 {
	if o == nil || IsNil(o.LastCompletion) {
		var ret int64
		return ret
	}
	return *o.LastCompletion
}

// GetLastCompletionOk returns a tuple with the LastCompletion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SkyBlockProfileMemberNetherIslandPlayerQuestsSuusQuest) GetLastCompletionOk() (*int64, bool) {
	if o == nil || IsNil(o.LastCompletion) {
		return nil, false
	}
	return o.LastCompletion, true
}

// HasLastCompletion returns a boolean if a field has been set.
func (o *SkyBlockProfileMemberNetherIslandPlayerQuestsSuusQuest) HasLastCompletion() bool {
	if o != nil && !IsNil(o.LastCompletion) {
		return true
	}

	return false
}

// SetLastCompletion gets a reference to the given int64 and assigns it to the LastCompletion field.
func (o *SkyBlockProfileMemberNetherIslandPlayerQuestsSuusQuest) SetLastCompletion(v int64) {
	o.LastCompletion = &v
}

// GetLastToyDrop returns the LastToyDrop field value if set, zero value otherwise.
func (o *SkyBlockProfileMemberNetherIslandPlayerQuestsSuusQuest) GetLastToyDrop() int64 {
	if o == nil || IsNil(o.LastToyDrop) {
		var ret int64
		return ret
	}
	return *o.LastToyDrop
}

// GetLastToyDropOk returns a tuple with the LastToyDrop field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SkyBlockProfileMemberNetherIslandPlayerQuestsSuusQuest) GetLastToyDropOk() (*int64, bool) {
	if o == nil || IsNil(o.LastToyDrop) {
		return nil, false
	}
	return o.LastToyDrop, true
}

// HasLastToyDrop returns a boolean if a field has been set.
func (o *SkyBlockProfileMemberNetherIslandPlayerQuestsSuusQuest) HasLastToyDrop() bool {
	if o != nil && !IsNil(o.LastToyDrop) {
		return true
	}

	return false
}

// SetLastToyDrop gets a reference to the given int64 and assigns it to the LastToyDrop field.
func (o *SkyBlockProfileMemberNetherIslandPlayerQuestsSuusQuest) SetLastToyDrop(v int64) {
	o.LastToyDrop = &v
}

// GetTalkedToNpc returns the TalkedToNpc field value if set, zero value otherwise.
func (o *SkyBlockProfileMemberNetherIslandPlayerQuestsSuusQuest) GetTalkedToNpc() bool {
	if o == nil || IsNil(o.TalkedToNpc) {
		var ret bool
		return ret
	}
	return *o.TalkedToNpc
}

// GetTalkedToNpcOk returns a tuple with the TalkedToNpc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SkyBlockProfileMemberNetherIslandPlayerQuestsSuusQuest) GetTalkedToNpcOk() (*bool, bool) {
	if o == nil || IsNil(o.TalkedToNpc) {
		return nil, false
	}
	return o.TalkedToNpc, true
}

// HasTalkedToNpc returns a boolean if a field has been set.
func (o *SkyBlockProfileMemberNetherIslandPlayerQuestsSuusQuest) HasTalkedToNpc() bool {
	if o != nil && !IsNil(o.TalkedToNpc) {
		return true
	}

	return false
}

// SetTalkedToNpc gets a reference to the given bool and assigns it to the TalkedToNpc field.
func (o *SkyBlockProfileMemberNetherIslandPlayerQuestsSuusQuest) SetTalkedToNpc(v bool) {
	o.TalkedToNpc = &v
}

func (o SkyBlockProfileMemberNetherIslandPlayerQuestsSuusQuest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SkyBlockProfileMemberNetherIslandPlayerQuestsSuusQuest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.LastCompletion) {
		toSerialize["last_completion"] = o.LastCompletion
	}
	if !IsNil(o.LastToyDrop) {
		toSerialize["last_toy_drop"] = o.LastToyDrop
	}
	if !IsNil(o.TalkedToNpc) {
		toSerialize["talked_to_npc"] = o.TalkedToNpc
	}
	return toSerialize, nil
}

type NullableSkyBlockProfileMemberNetherIslandPlayerQuestsSuusQuest struct {
	value *SkyBlockProfileMemberNetherIslandPlayerQuestsSuusQuest
	isSet bool
}

func (v NullableSkyBlockProfileMemberNetherIslandPlayerQuestsSuusQuest) Get() *SkyBlockProfileMemberNetherIslandPlayerQuestsSuusQuest {
	return v.value
}

func (v *NullableSkyBlockProfileMemberNetherIslandPlayerQuestsSuusQuest) Set(val *SkyBlockProfileMemberNetherIslandPlayerQuestsSuusQuest) {
	v.value = val
	v.isSet = true
}

func (v NullableSkyBlockProfileMemberNetherIslandPlayerQuestsSuusQuest) IsSet() bool {
	return v.isSet
}

func (v *NullableSkyBlockProfileMemberNetherIslandPlayerQuestsSuusQuest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSkyBlockProfileMemberNetherIslandPlayerQuestsSuusQuest(val *SkyBlockProfileMemberNetherIslandPlayerQuestsSuusQuest) *NullableSkyBlockProfileMemberNetherIslandPlayerQuestsSuusQuest {
	return &NullableSkyBlockProfileMemberNetherIslandPlayerQuestsSuusQuest{value: val, isSet: true}
}

func (v NullableSkyBlockProfileMemberNetherIslandPlayerQuestsSuusQuest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSkyBlockProfileMemberNetherIslandPlayerQuestsSuusQuest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
