/*
Hypixel Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContact type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContact{}

// SkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContact struct for SkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContact
type SkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContact struct {
	CompletedQuest     *bool                                                                                         `json:"completed_quest,omitempty"`
	DndEnabled         *bool                                                                                         `json:"dnd_enabled,omitempty"`
	IncomingCallsCount *int64                                                                                        `json:"incoming_calls_count,omitempty"`
	LastCall           *int64                                                                                        `json:"last_call,omitempty"`
	LastCallIncoming   *int64                                                                                        `json:"last_call_incoming,omitempty"`
	Specific           map[string]SkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContactSpecificValue `json:"specific,omitempty"`
	TalkedTo           *bool                                                                                         `json:"talked_to,omitempty"`
}

// NewSkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContact instantiates a new SkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContact object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContact() *SkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContact {
	this := SkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContact{}
	return &this
}

// NewSkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContactWithDefaults instantiates a new SkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContact object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContactWithDefaults() *SkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContact {
	this := SkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContact{}
	return &this
}

// GetCompletedQuest returns the CompletedQuest field value if set, zero value otherwise.
func (o *SkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContact) GetCompletedQuest() bool {
	if o == nil || IsNil(o.CompletedQuest) {
		var ret bool
		return ret
	}
	return *o.CompletedQuest
}

// GetCompletedQuestOk returns a tuple with the CompletedQuest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContact) GetCompletedQuestOk() (*bool, bool) {
	if o == nil || IsNil(o.CompletedQuest) {
		return nil, false
	}
	return o.CompletedQuest, true
}

// HasCompletedQuest returns a boolean if a field has been set.
func (o *SkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContact) HasCompletedQuest() bool {
	if o != nil && !IsNil(o.CompletedQuest) {
		return true
	}

	return false
}

// SetCompletedQuest gets a reference to the given bool and assigns it to the CompletedQuest field.
func (o *SkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContact) SetCompletedQuest(v bool) {
	o.CompletedQuest = &v
}

// GetDndEnabled returns the DndEnabled field value if set, zero value otherwise.
func (o *SkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContact) GetDndEnabled() bool {
	if o == nil || IsNil(o.DndEnabled) {
		var ret bool
		return ret
	}
	return *o.DndEnabled
}

// GetDndEnabledOk returns a tuple with the DndEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContact) GetDndEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.DndEnabled) {
		return nil, false
	}
	return o.DndEnabled, true
}

// HasDndEnabled returns a boolean if a field has been set.
func (o *SkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContact) HasDndEnabled() bool {
	if o != nil && !IsNil(o.DndEnabled) {
		return true
	}

	return false
}

// SetDndEnabled gets a reference to the given bool and assigns it to the DndEnabled field.
func (o *SkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContact) SetDndEnabled(v bool) {
	o.DndEnabled = &v
}

// GetIncomingCallsCount returns the IncomingCallsCount field value if set, zero value otherwise.
func (o *SkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContact) GetIncomingCallsCount() int64 {
	if o == nil || IsNil(o.IncomingCallsCount) {
		var ret int64
		return ret
	}
	return *o.IncomingCallsCount
}

// GetIncomingCallsCountOk returns a tuple with the IncomingCallsCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContact) GetIncomingCallsCountOk() (*int64, bool) {
	if o == nil || IsNil(o.IncomingCallsCount) {
		return nil, false
	}
	return o.IncomingCallsCount, true
}

// HasIncomingCallsCount returns a boolean if a field has been set.
func (o *SkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContact) HasIncomingCallsCount() bool {
	if o != nil && !IsNil(o.IncomingCallsCount) {
		return true
	}

	return false
}

// SetIncomingCallsCount gets a reference to the given int64 and assigns it to the IncomingCallsCount field.
func (o *SkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContact) SetIncomingCallsCount(v int64) {
	o.IncomingCallsCount = &v
}

// GetLastCall returns the LastCall field value if set, zero value otherwise.
func (o *SkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContact) GetLastCall() int64 {
	if o == nil || IsNil(o.LastCall) {
		var ret int64
		return ret
	}
	return *o.LastCall
}

// GetLastCallOk returns a tuple with the LastCall field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContact) GetLastCallOk() (*int64, bool) {
	if o == nil || IsNil(o.LastCall) {
		return nil, false
	}
	return o.LastCall, true
}

// HasLastCall returns a boolean if a field has been set.
func (o *SkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContact) HasLastCall() bool {
	if o != nil && !IsNil(o.LastCall) {
		return true
	}

	return false
}

// SetLastCall gets a reference to the given int64 and assigns it to the LastCall field.
func (o *SkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContact) SetLastCall(v int64) {
	o.LastCall = &v
}

// GetLastCallIncoming returns the LastCallIncoming field value if set, zero value otherwise.
func (o *SkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContact) GetLastCallIncoming() int64 {
	if o == nil || IsNil(o.LastCallIncoming) {
		var ret int64
		return ret
	}
	return *o.LastCallIncoming
}

// GetLastCallIncomingOk returns a tuple with the LastCallIncoming field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContact) GetLastCallIncomingOk() (*int64, bool) {
	if o == nil || IsNil(o.LastCallIncoming) {
		return nil, false
	}
	return o.LastCallIncoming, true
}

// HasLastCallIncoming returns a boolean if a field has been set.
func (o *SkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContact) HasLastCallIncoming() bool {
	if o != nil && !IsNil(o.LastCallIncoming) {
		return true
	}

	return false
}

// SetLastCallIncoming gets a reference to the given int64 and assigns it to the LastCallIncoming field.
func (o *SkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContact) SetLastCallIncoming(v int64) {
	o.LastCallIncoming = &v
}

// GetSpecific returns the Specific field value if set, zero value otherwise.
func (o *SkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContact) GetSpecific() map[string]SkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContactSpecificValue {
	if o == nil || IsNil(o.Specific) {
		var ret map[string]SkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContactSpecificValue
		return ret
	}
	return o.Specific
}

// GetSpecificOk returns a tuple with the Specific field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContact) GetSpecificOk() (map[string]SkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContactSpecificValue, bool) {
	if o == nil || IsNil(o.Specific) {
		return map[string]SkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContactSpecificValue{}, false
	}
	return o.Specific, true
}

// HasSpecific returns a boolean if a field has been set.
func (o *SkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContact) HasSpecific() bool {
	if o != nil && !IsNil(o.Specific) {
		return true
	}

	return false
}

// SetSpecific gets a reference to the given map[string]SkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContactSpecificValue and assigns it to the Specific field.
func (o *SkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContact) SetSpecific(v map[string]SkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContactSpecificValue) {
	o.Specific = v
}

// GetTalkedTo returns the TalkedTo field value if set, zero value otherwise.
func (o *SkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContact) GetTalkedTo() bool {
	if o == nil || IsNil(o.TalkedTo) {
		var ret bool
		return ret
	}
	return *o.TalkedTo
}

// GetTalkedToOk returns a tuple with the TalkedTo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContact) GetTalkedToOk() (*bool, bool) {
	if o == nil || IsNil(o.TalkedTo) {
		return nil, false
	}
	return o.TalkedTo, true
}

// HasTalkedTo returns a boolean if a field has been set.
func (o *SkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContact) HasTalkedTo() bool {
	if o != nil && !IsNil(o.TalkedTo) {
		return true
	}

	return false
}

// SetTalkedTo gets a reference to the given bool and assigns it to the TalkedTo field.
func (o *SkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContact) SetTalkedTo(v bool) {
	o.TalkedTo = &v
}

func (o SkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContact) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContact) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CompletedQuest) {
		toSerialize["completed_quest"] = o.CompletedQuest
	}
	if !IsNil(o.DndEnabled) {
		toSerialize["dnd_enabled"] = o.DndEnabled
	}
	if !IsNil(o.IncomingCallsCount) {
		toSerialize["incoming_calls_count"] = o.IncomingCallsCount
	}
	if !IsNil(o.LastCall) {
		toSerialize["last_call"] = o.LastCall
	}
	if !IsNil(o.LastCallIncoming) {
		toSerialize["last_call_incoming"] = o.LastCallIncoming
	}
	if !IsNil(o.Specific) {
		toSerialize["specific"] = o.Specific
	}
	if !IsNil(o.TalkedTo) {
		toSerialize["talked_to"] = o.TalkedTo
	}
	return toSerialize, nil
}

type NullableSkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContact struct {
	value *SkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContact
	isSet bool
}

func (v NullableSkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContact) Get() *SkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContact {
	return v.value
}

func (v *NullableSkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContact) Set(val *SkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContact) {
	v.value = val
	v.isSet = true
}

func (v NullableSkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContact) IsSet() bool {
	return v.isSet
}

func (v *NullableSkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContact) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContact(val *SkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContact) *NullableSkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContact {
	return &NullableSkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContact{value: val, isSet: true}
}

func (v NullableSkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContact) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSkyBlockProfileMemberNetherIslandPlayerDataAbiphoneContactDataContact) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
