/*
Hypixel Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SkyBlockProfileMemberDungeonsDungeonTypes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SkyBlockProfileMemberDungeonsDungeonTypes{}

// SkyBlockProfileMemberDungeonsDungeonTypes struct for SkyBlockProfileMemberDungeonsDungeonTypes
type SkyBlockProfileMemberDungeonsDungeonTypes struct {
	Catacombs       SkyBlockProfileMemberDungeonsDungeonTypesType  `json:"catacombs"`
	MasterCatacombs *SkyBlockProfileMemberDungeonsDungeonTypesType `json:"master_catacombs,omitempty"`
}

type _SkyBlockProfileMemberDungeonsDungeonTypes SkyBlockProfileMemberDungeonsDungeonTypes

// NewSkyBlockProfileMemberDungeonsDungeonTypes instantiates a new SkyBlockProfileMemberDungeonsDungeonTypes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSkyBlockProfileMemberDungeonsDungeonTypes(catacombs SkyBlockProfileMemberDungeonsDungeonTypesType) *SkyBlockProfileMemberDungeonsDungeonTypes {
	this := SkyBlockProfileMemberDungeonsDungeonTypes{}
	this.Catacombs = catacombs
	return &this
}

// NewSkyBlockProfileMemberDungeonsDungeonTypesWithDefaults instantiates a new SkyBlockProfileMemberDungeonsDungeonTypes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSkyBlockProfileMemberDungeonsDungeonTypesWithDefaults() *SkyBlockProfileMemberDungeonsDungeonTypes {
	this := SkyBlockProfileMemberDungeonsDungeonTypes{}
	return &this
}

// GetCatacombs returns the Catacombs field value
func (o *SkyBlockProfileMemberDungeonsDungeonTypes) GetCatacombs() SkyBlockProfileMemberDungeonsDungeonTypesType {
	if o == nil {
		var ret SkyBlockProfileMemberDungeonsDungeonTypesType
		return ret
	}

	return o.Catacombs
}

// GetCatacombsOk returns a tuple with the Catacombs field value
// and a boolean to check if the value has been set.
func (o *SkyBlockProfileMemberDungeonsDungeonTypes) GetCatacombsOk() (*SkyBlockProfileMemberDungeonsDungeonTypesType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Catacombs, true
}

// SetCatacombs sets field value
func (o *SkyBlockProfileMemberDungeonsDungeonTypes) SetCatacombs(v SkyBlockProfileMemberDungeonsDungeonTypesType) {
	o.Catacombs = v
}

// GetMasterCatacombs returns the MasterCatacombs field value if set, zero value otherwise.
func (o *SkyBlockProfileMemberDungeonsDungeonTypes) GetMasterCatacombs() SkyBlockProfileMemberDungeonsDungeonTypesType {
	if o == nil || IsNil(o.MasterCatacombs) {
		var ret SkyBlockProfileMemberDungeonsDungeonTypesType
		return ret
	}
	return *o.MasterCatacombs
}

// GetMasterCatacombsOk returns a tuple with the MasterCatacombs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SkyBlockProfileMemberDungeonsDungeonTypes) GetMasterCatacombsOk() (*SkyBlockProfileMemberDungeonsDungeonTypesType, bool) {
	if o == nil || IsNil(o.MasterCatacombs) {
		return nil, false
	}
	return o.MasterCatacombs, true
}

// HasMasterCatacombs returns a boolean if a field has been set.
func (o *SkyBlockProfileMemberDungeonsDungeonTypes) HasMasterCatacombs() bool {
	if o != nil && !IsNil(o.MasterCatacombs) {
		return true
	}

	return false
}

// SetMasterCatacombs gets a reference to the given SkyBlockProfileMemberDungeonsDungeonTypesType and assigns it to the MasterCatacombs field.
func (o *SkyBlockProfileMemberDungeonsDungeonTypes) SetMasterCatacombs(v SkyBlockProfileMemberDungeonsDungeonTypesType) {
	o.MasterCatacombs = &v
}

func (o SkyBlockProfileMemberDungeonsDungeonTypes) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SkyBlockProfileMemberDungeonsDungeonTypes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["catacombs"] = o.Catacombs
	if !IsNil(o.MasterCatacombs) {
		toSerialize["master_catacombs"] = o.MasterCatacombs
	}
	return toSerialize, nil
}

func (o *SkyBlockProfileMemberDungeonsDungeonTypes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"catacombs",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSkyBlockProfileMemberDungeonsDungeonTypes := _SkyBlockProfileMemberDungeonsDungeonTypes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSkyBlockProfileMemberDungeonsDungeonTypes)

	if err != nil {
		return err
	}

	*o = SkyBlockProfileMemberDungeonsDungeonTypes(varSkyBlockProfileMemberDungeonsDungeonTypes)

	return err
}

type NullableSkyBlockProfileMemberDungeonsDungeonTypes struct {
	value *SkyBlockProfileMemberDungeonsDungeonTypes
	isSet bool
}

func (v NullableSkyBlockProfileMemberDungeonsDungeonTypes) Get() *SkyBlockProfileMemberDungeonsDungeonTypes {
	return v.value
}

func (v *NullableSkyBlockProfileMemberDungeonsDungeonTypes) Set(val *SkyBlockProfileMemberDungeonsDungeonTypes) {
	v.value = val
	v.isSet = true
}

func (v NullableSkyBlockProfileMemberDungeonsDungeonTypes) IsSet() bool {
	return v.isSet
}

func (v *NullableSkyBlockProfileMemberDungeonsDungeonTypes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSkyBlockProfileMemberDungeonsDungeonTypes(val *SkyBlockProfileMemberDungeonsDungeonTypes) *NullableSkyBlockProfileMemberDungeonsDungeonTypes {
	return &NullableSkyBlockProfileMemberDungeonsDungeonTypes{value: val, isSet: true}
}

func (v NullableSkyBlockProfileMemberDungeonsDungeonTypes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSkyBlockProfileMemberDungeonsDungeonTypes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
