/*
Hypixel Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SkyBlockProfileMemberRiftVillagePlazaMurderMurderSnapshotPet type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SkyBlockProfileMemberRiftVillagePlazaMurderMurderSnapshotPet{}

// SkyBlockProfileMemberRiftVillagePlazaMurderMurderSnapshotPet struct for SkyBlockProfileMemberRiftVillagePlazaMurderMurderSnapshotPet
type SkyBlockProfileMemberRiftVillagePlazaMurderMurderSnapshotPet struct {
	Exp  float64                                        `json:"exp"`
	Tier SkyBlockProfileMemberRiftDeadCatsMontezumaTier `json:"tier"`
	Type SkyBlockProfileMemberRiftDeadCatsMontezumaType `json:"type"`
}

type _SkyBlockProfileMemberRiftVillagePlazaMurderMurderSnapshotPet SkyBlockProfileMemberRiftVillagePlazaMurderMurderSnapshotPet

// NewSkyBlockProfileMemberRiftVillagePlazaMurderMurderSnapshotPet instantiates a new SkyBlockProfileMemberRiftVillagePlazaMurderMurderSnapshotPet object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSkyBlockProfileMemberRiftVillagePlazaMurderMurderSnapshotPet(exp float64, tier SkyBlockProfileMemberRiftDeadCatsMontezumaTier, type_ SkyBlockProfileMemberRiftDeadCatsMontezumaType) *SkyBlockProfileMemberRiftVillagePlazaMurderMurderSnapshotPet {
	this := SkyBlockProfileMemberRiftVillagePlazaMurderMurderSnapshotPet{}
	this.Exp = exp
	this.Tier = tier
	this.Type = type_
	return &this
}

// NewSkyBlockProfileMemberRiftVillagePlazaMurderMurderSnapshotPetWithDefaults instantiates a new SkyBlockProfileMemberRiftVillagePlazaMurderMurderSnapshotPet object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSkyBlockProfileMemberRiftVillagePlazaMurderMurderSnapshotPetWithDefaults() *SkyBlockProfileMemberRiftVillagePlazaMurderMurderSnapshotPet {
	this := SkyBlockProfileMemberRiftVillagePlazaMurderMurderSnapshotPet{}
	return &this
}

// GetExp returns the Exp field value
func (o *SkyBlockProfileMemberRiftVillagePlazaMurderMurderSnapshotPet) GetExp() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Exp
}

// GetExpOk returns a tuple with the Exp field value
// and a boolean to check if the value has been set.
func (o *SkyBlockProfileMemberRiftVillagePlazaMurderMurderSnapshotPet) GetExpOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Exp, true
}

// SetExp sets field value
func (o *SkyBlockProfileMemberRiftVillagePlazaMurderMurderSnapshotPet) SetExp(v float64) {
	o.Exp = v
}

// GetTier returns the Tier field value
func (o *SkyBlockProfileMemberRiftVillagePlazaMurderMurderSnapshotPet) GetTier() SkyBlockProfileMemberRiftDeadCatsMontezumaTier {
	if o == nil {
		var ret SkyBlockProfileMemberRiftDeadCatsMontezumaTier
		return ret
	}

	return o.Tier
}

// GetTierOk returns a tuple with the Tier field value
// and a boolean to check if the value has been set.
func (o *SkyBlockProfileMemberRiftVillagePlazaMurderMurderSnapshotPet) GetTierOk() (*SkyBlockProfileMemberRiftDeadCatsMontezumaTier, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tier, true
}

// SetTier sets field value
func (o *SkyBlockProfileMemberRiftVillagePlazaMurderMurderSnapshotPet) SetTier(v SkyBlockProfileMemberRiftDeadCatsMontezumaTier) {
	o.Tier = v
}

// GetType returns the Type field value
func (o *SkyBlockProfileMemberRiftVillagePlazaMurderMurderSnapshotPet) GetType() SkyBlockProfileMemberRiftDeadCatsMontezumaType {
	if o == nil {
		var ret SkyBlockProfileMemberRiftDeadCatsMontezumaType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *SkyBlockProfileMemberRiftVillagePlazaMurderMurderSnapshotPet) GetTypeOk() (*SkyBlockProfileMemberRiftDeadCatsMontezumaType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *SkyBlockProfileMemberRiftVillagePlazaMurderMurderSnapshotPet) SetType(v SkyBlockProfileMemberRiftDeadCatsMontezumaType) {
	o.Type = v
}

func (o SkyBlockProfileMemberRiftVillagePlazaMurderMurderSnapshotPet) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SkyBlockProfileMemberRiftVillagePlazaMurderMurderSnapshotPet) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["exp"] = o.Exp
	toSerialize["tier"] = o.Tier
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *SkyBlockProfileMemberRiftVillagePlazaMurderMurderSnapshotPet) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"exp",
		"tier",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSkyBlockProfileMemberRiftVillagePlazaMurderMurderSnapshotPet := _SkyBlockProfileMemberRiftVillagePlazaMurderMurderSnapshotPet{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSkyBlockProfileMemberRiftVillagePlazaMurderMurderSnapshotPet)

	if err != nil {
		return err
	}

	*o = SkyBlockProfileMemberRiftVillagePlazaMurderMurderSnapshotPet(varSkyBlockProfileMemberRiftVillagePlazaMurderMurderSnapshotPet)

	return err
}

type NullableSkyBlockProfileMemberRiftVillagePlazaMurderMurderSnapshotPet struct {
	value *SkyBlockProfileMemberRiftVillagePlazaMurderMurderSnapshotPet
	isSet bool
}

func (v NullableSkyBlockProfileMemberRiftVillagePlazaMurderMurderSnapshotPet) Get() *SkyBlockProfileMemberRiftVillagePlazaMurderMurderSnapshotPet {
	return v.value
}

func (v *NullableSkyBlockProfileMemberRiftVillagePlazaMurderMurderSnapshotPet) Set(val *SkyBlockProfileMemberRiftVillagePlazaMurderMurderSnapshotPet) {
	v.value = val
	v.isSet = true
}

func (v NullableSkyBlockProfileMemberRiftVillagePlazaMurderMurderSnapshotPet) IsSet() bool {
	return v.isSet
}

func (v *NullableSkyBlockProfileMemberRiftVillagePlazaMurderMurderSnapshotPet) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSkyBlockProfileMemberRiftVillagePlazaMurderMurderSnapshotPet(val *SkyBlockProfileMemberRiftVillagePlazaMurderMurderSnapshotPet) *NullableSkyBlockProfileMemberRiftVillagePlazaMurderMurderSnapshotPet {
	return &NullableSkyBlockProfileMemberRiftVillagePlazaMurderMurderSnapshotPet{value: val, isSet: true}
}

func (v NullableSkyBlockProfileMemberRiftVillagePlazaMurderMurderSnapshotPet) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSkyBlockProfileMemberRiftVillagePlazaMurderMurderSnapshotPet) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
