/*
Hypixel Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the V2SkyblockGardenGet422Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V2SkyblockGardenGet422Response{}

// V2SkyblockGardenGet422Response struct for V2SkyblockGardenGet422Response
type V2SkyblockGardenGet422Response struct {
	Cause   *string `json:"cause,omitempty"`
	Success *bool   `json:"success,omitempty"`
}

// NewV2SkyblockGardenGet422Response instantiates a new V2SkyblockGardenGet422Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2SkyblockGardenGet422Response() *V2SkyblockGardenGet422Response {
	this := V2SkyblockGardenGet422Response{}
	return &this
}

// NewV2SkyblockGardenGet422ResponseWithDefaults instantiates a new V2SkyblockGardenGet422Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2SkyblockGardenGet422ResponseWithDefaults() *V2SkyblockGardenGet422Response {
	this := V2SkyblockGardenGet422Response{}
	return &this
}

// GetCause returns the Cause field value if set, zero value otherwise.
func (o *V2SkyblockGardenGet422Response) GetCause() string {
	if o == nil || IsNil(o.Cause) {
		var ret string
		return ret
	}
	return *o.Cause
}

// GetCauseOk returns a tuple with the Cause field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2SkyblockGardenGet422Response) GetCauseOk() (*string, bool) {
	if o == nil || IsNil(o.Cause) {
		return nil, false
	}
	return o.Cause, true
}

// HasCause returns a boolean if a field has been set.
func (o *V2SkyblockGardenGet422Response) HasCause() bool {
	if o != nil && !IsNil(o.Cause) {
		return true
	}

	return false
}

// SetCause gets a reference to the given string and assigns it to the Cause field.
func (o *V2SkyblockGardenGet422Response) SetCause(v string) {
	o.Cause = &v
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *V2SkyblockGardenGet422Response) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2SkyblockGardenGet422Response) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *V2SkyblockGardenGet422Response) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *V2SkyblockGardenGet422Response) SetSuccess(v bool) {
	o.Success = &v
}

func (o V2SkyblockGardenGet422Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V2SkyblockGardenGet422Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Cause) {
		toSerialize["cause"] = o.Cause
	}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	return toSerialize, nil
}

type NullableV2SkyblockGardenGet422Response struct {
	value *V2SkyblockGardenGet422Response
	isSet bool
}

func (v NullableV2SkyblockGardenGet422Response) Get() *V2SkyblockGardenGet422Response {
	return v.value
}

func (v *NullableV2SkyblockGardenGet422Response) Set(val *V2SkyblockGardenGet422Response) {
	v.value = val
	v.isSet = true
}

func (v NullableV2SkyblockGardenGet422Response) IsSet() bool {
	return v.isSet
}

func (v *NullableV2SkyblockGardenGet422Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2SkyblockGardenGet422Response(val *V2SkyblockGardenGet422Response) *NullableV2SkyblockGardenGet422Response {
	return &NullableV2SkyblockGardenGet422Response{value: val, isSet: true}
}

func (v NullableV2SkyblockGardenGet422Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2SkyblockGardenGet422Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
